export const carMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "mercedes", label: "Mercedes-Benz" },
      { value: "bmw", label: "BMW" },
      { value: "audi", label: "Audi" },
      { value: "volkswagen", label: "Volkswagen" },
      { value: "porsche", label: "Porsche" },
      { value: "ford", label: "Ford" },
      { value: "skoda", label: "Skoda" },
      { value: "opel", label: "Opel" },
      { value: "toyota", label: "Toyota" },
      { value: "volvo", label: "Volvo" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "9ff", label: "9ff" },
      { value: "abarth", label: "Abarth" },
      { value: "ac", label: "AC" },
      { value: "acm", label: "ACM" },
      { value: "acura", label: "Acura" },
      { value: "aerfal", label: "Aerfal" },
      { value: "aiways", label: "Aiways" },
      { value: "aixam", label: "Aixam" },
      { value: "alba-mobility", label: "Alba Mobility" },
      { value: "alfa-romeo", label: "Alfa Romeo" },
      { value: "alpina", label: "Alpina" },
      { value: "alpine", label: "Alpine" },
      { value: "amphicar", label: "Amphicar" },
      { value: "angelelli-automobili", label: "Angelelli Automobili" },
      { value: "ariel-motor", label: "Ariel Motor" },
      { value: "artega", label: "Artega" },
      { value: "aspark", label: "Aspark" },
      { value: "aspid", label: "Aspid" },
      { value: "aston-martin", label: "Aston Martin" },

      { value: "aurus", label: "Aurus" },
      { value: "austin", label: "Austin" },
      { value: "austin-healey", label: "Austin-Healey" },
      { value: "autobianchi", label: "Autobianchi" },
      { value: "baic", label: "BAIC" },
      { value: "baw", label: "BAW" },
      { value: "bedford", label: "Bedford" },
      { value: "bellier", label: "Bellier" },
      { value: "bentley", label: "Bentley" },
      { value: "bertone", label: "Bertone" },
      { value: "bestune", label: "Bestune" },

      { value: "boldmen", label: "Boldmen" },
      { value: "bollore", label: "Bolloré" },
      { value: "borgward", label: "Borgward" },
      { value: "brilliance", label: "Brilliance" },
      { value: "bristol", label: "Bristol" },
      { value: "brute", label: "Brute" },
      { value: "bugatti", label: "Bugatti" },
      { value: "buick", label: "Buick" },
      { value: "byd", label: "BYD" },
      { value: "cadillac", label: "Cadillac" },
      { value: "caravans-wohnm", label: "Caravans-Wohnm" },
      { value: "carver", label: "Carver" },
      { value: "casalini", label: "Casalini" },
      { value: "caterham", label: "Caterham" },
      { value: "cenntro", label: "Cenntro" },
      { value: "chamonix", label: "Chamonix" },
      { value: "changan", label: "Changan" },
      { value: "changhe", label: "Changhe" },
      { value: "chatenet", label: "Chatenet" },
      { value: "chery", label: "Chery" },
      { value: "chevrolet", label: "Chevrolet" },
      { value: "chrysler", label: "Chrysler" },
      { value: "cirelli", label: "Cirelli" },
      { value: "citroen", label: "Citroen" },
      { value: "cityel", label: "CityEL" },
      { value: "corvette", label: "Corvette" },
      { value: "cupra", label: "CUPRA" },
      { value: "dacia", label: "Dacia" },
      { value: "daewoo", label: "Daewoo" },
      { value: "daf", label: "DAF" },
      { value: "daihatsu", label: "Daihatsu" },
      { value: "daimler", label: "Daimler" },
      { value: "dallara", label: "Dallara" },
      { value: "dangel", label: "Dangel" },
      { value: "de-la-chapelle", label: "De la Chapelle" },
      { value: "de-tomaso", label: "De Tomaso" },
      { value: "delorean", label: "Delorean" },
      { value: "denza", label: "Denza" },
      { value: "devinci-cars", label: "Devinci Cars" },
      { value: "dfsk", label: "DFSK" },
      { value: "dodge", label: "Dodge" },
      { value: "dongfeng", label: "Dongfeng" },
      { value: "donkervoort", label: "Donkervoort" },
      { value: "dr-automobiles", label: "DR Automobiles" },
      { value: "ds-automobiles", label: "DS Automobiles" },
      { value: "dutton", label: "Dutton" },
      { value: "e-go", label: "e.GO" },
      { value: "ebro", label: "Ebro" },
      { value: "econelo", label: "Econelo" },
      { value: "edran", label: "Edran" },
      { value: "elaris", label: "Elaris" },
      { value: "embuggy", label: "Embuggy" },
      { value: "emc", label: "EMC" },
      { value: "estrima", label: "Estrima" },
      { value: "evetta", label: "Evetta" },
      { value: "evo", label: "EVO" },
      { value: "farizon", label: "Farizon" },
      { value: "ferrari", label: "Ferrari" },
      { value: "fiat", label: "Fiat" },
      { value: "fisker", label: "Fisker" },

      { value: "forthing", label: "Forthing" },
      { value: "foton", label: "Foton" },
      { value: "gac-gonow", label: "Gac Gonow" },
      { value: "galloper", label: "Galloper" },
      { value: "gappy", label: "Gappy" },
      { value: "gaz", label: "GAZ" },
      { value: "geely", label: "Geely" },
      { value: "gem", label: "GEM" },
      { value: "gemballa", label: "GEMBALLA" },
      { value: "genesis", label: "Genesis" },
      { value: "giana", label: "Giana" },
      { value: "gillet", label: "Gillet" },
      { value: "giotti-victoria", label: "Giotti Victoria" },
      { value: "gmc", label: "GMC" },
      { value: "goupil", label: "Goupil" },
      { value: "great-wall", label: "Great Wall" },
      { value: "grecav", label: "Grecav" },
      { value: "gta", label: "GTA" },
      { value: "gwm", label: "GWM" },
      { value: "haima", label: "Haima" },
      { value: "hamann", label: "Hamann" },
      { value: "haval", label: "Haval" },
      { value: "hiphi", label: "Hiphi" },
      { value: "holden", label: "Holden" },
      { value: "honda", label: "Honda" },
      { value: "hongqi", label: "Hongqi" },
      { value: "hummer", label: "HUMMER" },
      { value: "hurtan", label: "Hurtan" },
      { value: "hyundai", label: "Hyundai" },
      { value: "ich-x", label: "ICH-X" },
      { value: "ineos", label: "Ineos" },
      { value: "infiniti", label: "Infiniti" },
      { value: "innocenti", label: "Innocenti" },
      { value: "invicta", label: "Invicta" },
      { value: "iso-rivolta", label: "Iso Rivolta" },
      { value: "isuzu", label: "Isuzu" },
      { value: "iveco", label: "Iveco" },
      { value: "izh", label: "IZH" },
      { value: "jac", label: "JAC" },
      { value: "jaecoo", label: "Jaecoo" },
      { value: "jaguar", label: "Jaguar" },
      { value: "jeep", label: "Jeep" },
      { value: "jensen", label: "Jensen" },
      { value: "karma", label: "Karma" },
      { value: "kgm", label: "KGM" },
      { value: "kia", label: "Kia" },
      { value: "koenigsegg", label: "Koenigsegg" },
      { value: "ktm", label: "KTM" },
      { value: "lada", label: "Lada" },
      { value: "lamborghini", label: "Lamborghini" },
      { value: "lancia", label: "Lancia" },
      { value: "land-rover", label: "Land Rover" },
      { value: "ldv", label: "LDV" },
      { value: "leapmotor", label: "Leapmotor" },
      { value: "lee-group", label: "Lee Group" },
      { value: "levc", label: "LEVC" },
      { value: "lexus", label: "Lexus" },
      { value: "li", label: "Li" },
      { value: "lifan", label: "Lifan" },
      { value: "ligier", label: "Ligier" },
      { value: "lincoln", label: "Lincoln" },
      { value: "linzda", label: "Linzda" },
      { value: "livan", label: "Livan" },
      { value: "lorinser", label: "Lorinser" },
      { value: "lotus", label: "Lotus" },
      { value: "lucid", label: "Lucid" },
      { value: "lynk-co", label: "Lynk & Co" },
      { value: "m-ero", label: "M-Ero" },
      { value: "mahindra", label: "Mahindra" },
      { value: "man", label: "MAN" },
      { value: "mansory", label: "Mansory" },
      { value: "martin", label: "Martin" },
      { value: "martin-motors", label: "Martin Motors" },
      { value: "maserati", label: "Maserati" },
      { value: "matra", label: "Matra" },
      { value: "maxus", label: "Maxus" },
      { value: "maybach", label: "Maybach" },
      { value: "mazda", label: "Mazda" },
      { value: "mclaren", label: "McLaren" },
      { value: "mega", label: "Mega" },
      { value: "melex", label: "Melex" },

      { value: "mercury", label: "Mercury" },
      { value: "mg", label: "MG" },
      { value: "micro", label: "Micro" },
      { value: "microcar", label: "Microcar" },
      { value: "militem", label: "Militem" },
      { value: "minari", label: "Minari" },
      { value: "minauto", label: "Minauto" },
      { value: "mini", label: "MINI" },
      { value: "mitsubishi", label: "Mitsubishi" },
      { value: "mitsuoka", label: "Mitsuoka" },
      { value: "mobilize", label: "Mobilize" },
      { value: "morgan", label: "Morgan" },
      { value: "moskvich", label: "Moskvich" },
      { value: "mp-lafer", label: "MP Lafer" },
      { value: "mpm-motors", label: "MPM Motors" },
      { value: "nio", label: "NIO" },
      { value: "nissan", label: "Nissan" },
      { value: "nsu", label: "NSU" },
      { value: "oldsmobile", label: "Oldsmobile" },
      { value: "oldtimer", label: "Oldtimer" },
      { value: "omoda", label: "Omoda" },

      { value: "ora", label: "Ora" },
      { value: "pagani", label: "Pagani" },
      { value: "panther-westwinds", label: "Panther Westwinds" },
      { value: "peugeot", label: "Peugeot" },
      { value: "pgo", label: "PGO" },
      { value: "piaggio", label: "Piaggio" },
      { value: "plymouth", label: "Plymouth" },
      { value: "polestar", label: "Polestar" },
      { value: "pontiac", label: "Pontiac" },
      { value: "proton", label: "Proton" },
      { value: "puch", label: "Puch" },
      { value: "ram", label: "RAM" },
      { value: "regis", label: "Regis" },
      { value: "reliant", label: "Reliant" },

      { value: "rivian", label: "Rivian" },
      { value: "rolls-royce", label: "Rolls-Royce" },
      { value: "rover", label: "Rover" },
      { value: "ruf", label: "Ruf" },
      { value: "saab", label: "Saab" },
      { value: "santana", label: "Santana" },
      { value: "seat", label: "SEAT" },
      { value: "segway", label: "Segway" },
      { value: "selvo", label: "Selvo" },
      { value: "seres", label: "Seres" },
      { value: "sevic", label: "Sevic" },
      { value: "sgs", label: "SGS" },
      { value: "shelby", label: "Shelby" },
      { value: "shuanghuan", label: "Shuanghuan" },
      { value: "silence", label: "Silence" },
      { value: "simplici", label: "Simplici" },
      { value: "singer", label: "Singer" },
      { value: "skywell", label: "Skywell" },
      { value: "smart", label: "smart" },
      { value: "speedart", label: "SpeedArt" },
      { value: "sportequipe", label: "Sportequipe" },
      { value: "spyker", label: "Spyker" },
      { value: "ssangyong", label: "SsangYong" },
      { value: "stormborn", label: "Stormborn" },
      { value: "streetscooter", label: "StreetScooter" },
      { value: "studebaker", label: "Studebaker" },
      { value: "subaru", label: "Subaru" },
      { value: "suzuki", label: "Suzuki" },
      { value: "swm", label: "SWM" },
      { value: "talbot", label: "Talbot" },
      { value: "tasso", label: "Tasso" },
      { value: "tata", label: "Tata" },
      { value: "tazzari-ev", label: "Tazzari EV" },
      { value: "techart", label: "TECHART" },
      { value: "tesla", label: "Tesla" },
      { value: "tiger", label: "Tiger" },
      { value: "togg", label: "Togg" },
      { value: "town-life", label: "Town Life" },
      { value: "trabant", label: "Trabant" },
      { value: "trailer-anhanger", label: "Trailer-Anhänger" },
      { value: "triumph", label: "Triumph" },
      { value: "trucks-lkw", label: "Trucks-Lkw" },
      { value: "tvr", label: "TVR" },
      { value: "uaz", label: "UAZ" },
      { value: "vanden-plas", label: "Vanden Plas" },
      { value: "vanderhall", label: "Vanderhall" },
      { value: "vaz", label: "VAZ" },
      { value: "vem", label: "VEM" },
      { value: "vinfast", label: "VinFast" },

      { value: "voyah", label: "Voyah" },
      { value: "wartburg", label: "Wartburg" },
      { value: "weltmeister", label: "Weltmeister" },
      { value: "wenckstern", label: "Wenckstern" },
      { value: "westfield", label: "Westfield" },
      { value: "wey", label: "Wey" },
      { value: "wiesmann", label: "Wiesmann" },
      { value: "xbus", label: "XBus" },
      { value: "xev", label: "XEV" },
      { value: "xiaomi", label: "Xiaomi" },
      { value: "xpeng", label: "Xpeng" },
      { value: "zastava", label: "Zastava" },
      { value: "zaz", label: "ZAZ" },
      { value: "zeekr", label: "Zeekr" },
      { value: "zhidou", label: "Zhidou" },
      { value: "zotye", label: "Zotye" },
      { value: "others", label: "Others" },
    ],
  },
] as const;

export const carModels: Record<string, { value: string; label: string }[]> = {
  audi: [
    { value: "a1", label: "A1" },
    { value: "a3", label: "A3" },
    { value: "a4", label: "A4" },
    { value: "a6", label: "A6" },
    { value: "a8", label: "A8" },
    { value: "q3", label: "Q3" },
    { value: "q5", label: "Q5" },
    { value: "q7", label: "Q7" },
    { value: "q8", label: "Q8" },
    { value: "tt", label: "TT" },
    { value: "r8", label: "R8" },
    { value: "e-tron", label: "e-tron" },
  ],
  bmw: [
    { value: "1-series", label: "1 Series" },
    { value: "2-series", label: "2 Series" },
    { value: "3-series", label: "3 Series" },
    { value: "4-series", label: "4 Series" },
    { value: "5-series", label: "5 Series" },
    { value: "7-series", label: "7 Series" },
    { value: "x1", label: "X1" },
    { value: "x3", label: "X3" },
    { value: "x5", label: "X5" },
    { value: "x7", label: "X7" },
    { value: "i4", label: "i4" },
    { value: "i8", label: "i8" },
    { value: "ix", label: "iX" },
  ],
  mercedes: [
    { value: "a-class", label: "A-Class" },
    { value: "c-class", label: "C-Class" },
    { value: "e-class", label: "E-Class" },
    { value: "s-class", label: "S-Class" },
    { value: "gla", label: "GLA" },
    { value: "glb", label: "GLB" },
    { value: "glc", label: "GLC" },
    { value: "gle", label: "GLE" },
    { value: "gls", label: "GLS" },
    { value: "eqc", label: "EQC" },
    { value: "eqs", label: "EQS" },
  ],
  volkswagen: [
    { value: "golf", label: "Golf" },
    { value: "polo", label: "Polo" },
    { value: "passat", label: "Passat" },
    { value: "tiguan", label: "Tiguan" },
    { value: "touareg", label: "Touareg" },
    { value: "t-roc", label: "T-Roc" },
    { value: "arteon", label: "Arteon" },
    { value: "id3", label: "ID.3" },
    { value: "id4", label: "ID.4" },
  ],
  porsche: [
    { value: "911", label: "911" },
    { value: "718", label: "718" },
    { value: "cayenne", label: "Cayenne" },
    { value: "macan", label: "Macan" },
    { value: "panamera", label: "Panamera" },
    { value: "taycan", label: "Taycan" },
  ],
  ford: [
    { value: "fiesta", label: "Fiesta" },
    { value: "focus", label: "Focus" },
    { value: "mustang", label: "Mustang" },
    { value: "explorer", label: "Explorer" },
    { value: "f150", label: "F-150" },
    { value: "ranger", label: "Ranger" },
    { value: "edge", label: "Edge" },
  ],
  toyota: [
    { value: "corolla", label: "Corolla" },
    { value: "camry", label: "Camry" },
    { value: "rav4", label: "RAV4" },
    { value: "highlander", label: "Highlander" },
    { value: "prius", label: "Prius" },
    { value: "landcruiser", label: "Land Cruiser" },
    { value: "yaris", label: "Yaris" },
  ],
  honda: [
    { value: "civic", label: "Civic" },
    { value: "accord", label: "Accord" },
    { value: "crv", label: "CR-V" },
    { value: "hrv", label: "HR-V" },
    { value: "pilot", label: "Pilot" },
    { value: "fit", label: "Fit" },
  ],
  nissan: [
    { value: "altima", label: "Altima" },
    { value: "maxima", label: "Maxima" },
    { value: "sentra", label: "Sentra" },
    { value: "rogue", label: "Rogue" },
    { value: "murano", label: "Murano" },
    { value: "pathfinder", label: "Pathfinder" },
    { value: "leaf", label: "Leaf" },
  ],
  hyundai: [
    { value: "elantra", label: "Elantra" },
    { value: "sonata", label: "Sonata" },
    { value: "tucson", label: "Tucson" },
    { value: "santa-fe", label: "Santa Fe" },
    { value: "kona", label: "Kona" },
    { value: "ioniq", label: "Ioniq" },
  ],
} as const;

export const popularCarMakes = [
  {
    name: "Mercedes-Benz",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/mercedes-benz.df6b0bf0.png?w=320&q=75",
  },
  {
    name: "BMW",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/bmw.d80d5e29.png?w=320&q=75",
  },
  {
    name: "Audi",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/audi.04e8f0dc.png?w=320&q=75",
  },
  {
    name: "VW",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/vw.81540e42.png?w=320&q=75",
  },
  {
    name: "Porsche",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/porsche.0adcb83f.png?w=320&q=75",
  },
  {
    name: "Toyota",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/toyota.9a8f48b4.png?w=320&q=75",
  },
  {
    name: "Ford",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/ford.8ebffc41.png?w=320&q=75",
  },
  {
    name: "Skoda",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/skoda.f1c9e839.png?w=320&q=75",
  },
  {
    name: "Renault",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/renault.35f93614.png?w=320&q=75",
  },
  {
    name: "Volvo",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/volvo.b9d848a4.png?w=320&q=75",
  },
  {
    name: "Fiat",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/fiat.2c8b543a.png?w=320&q=75",
  },
  {
    name: "Seat",
    logo: "https://assets.autoscout24.ch/l/_next/static/media/seat.8a3b4153.png?w=320&q=75",
  },
] as const;

export const carBodyTypeEnum = [
  { value: "bus", label: "Bus" },
  { value: "cabriolet", label: "Cabriolet" },
  { value: "coupe", label: "Coupé" },
  { value: "small-car", label: "Kleinwagen" },
  { value: "estate", label: "Kombi" },
  { value: "minivan", label: "Kompaktvan / Minivan" },
  { value: "saloon", label: "Limousine" },
  { value: "pickup", label: "Pick-up" },
  { value: "suv", label: "SUV / Geländewagen" },
] as const;

export const carFuelTypeEnum = [
  { value: "petrol", label: "Benzin" },
  { value: "ethanol-petrol", label: "Bioethanol" },
  { value: "diesel", label: "Diesel" },
  { value: "electric", label: "Elektro" },
  { value: "cng-petrol", label: "Erdgas (CNG) / Benzin" },
  { value: "lpg-petrol", label: "Flüssiggas (LPG) / Benzin" },
  { value: "mhev-diesel", label: "Mild-Hybrid Diesel/Elektro" },
  { value: "mhev-petrol", label: "Mild-Hybrid Benzin/Elektro" },
  { value: "phev-diesel", label: "Plug-in hybrid Diesel/Elektro" },
  { value: "phev-petrol", label: "Plug-in hybrid Benzin/Elektro" },
  { value: "hev-diesel", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "hev-petrol", label: "Voll-Hybrid Benzin/Elektro" },
  { value: "hydrogen", label: "Wasserstoff" },
] as const;

export const carExtrasEnum = [
  { value: "8-tyres", label: "8-fach bereift" },
  { value: "accessible-for-disabled", label: "Behindertengerecht" },
  { value: "direct-import", label: "Direkt-/Parallelimport" },
  { value: "race-car", label: "Rennwagen" },
  { value: "tuning", label: "Tuning" },
  { value: "accident-vehicle", label: "Unfallfahrzeug" },
] as const;
