export const GearTransmissionEnum = [
  { value: "automatic", label: "Automatikgetriebe" },
  { value: "manual", label: "Schaltgetriebe" },
] as const;

export const TransmissionTypeEnum = [
  { value: "automatic", label: "Automat" },
  { value: "automatic-stepless", label: "Stufenlos" },
  { value: "semi-automatic", label: "Halbautomatisches Getriebe" },
  { value: "manual", label: "Schaltgetriebe manuell" },
] as const;

export const DriveTypeEnum = [
  { value: "all", label: "Allrad" },
  { value: "front", label: "Hinterradantrieb" },
  { value: "rear", label: "Vorderradantrieb" },
] as const;

export const BodyTypeEnum = [
  { value: "estate", label: "Kombi" },
  { value: "cabriolet", label: "Cabriolet" },
  { value: "pickup", label: "Pick-up" },
  { value: "suv", label: "SUV / Geländewagen" },
  { value: "coupe", label: "Coupé" },
  { value: "minivan", label: "Kompaktvan / Minivan" },
  { value: "saloon", label: "Limousine" },
  { value: "small-car", label: "Kleinwagen" },
  { value: "bus", label: "Bus" },
] as const;

export const FuelTypeEnum = [
  { value: "petrol", label: "Benzin" },
  { value: "diesel", label: "Diesel" },
  { value: "electric", label: "Elektro" },
  { value: "hev-diesel", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "hev-petrol", label: "Voll-Hybrid Benzin/Elektro" },
  {
    value: "mhev-diesel",
    label: "Mild-Hybrid Diesel/Elektro",
  },
  {
    value: "mhev-petrol",
    label: "Mild-Hybrid Benzin/Elektro",
  },
  {
    value: "phev-diesel",
    label: "Plug-in hybrid Diesel/Elektro",
  },
  {
    value: "phev-petrol",
    label: "Plug-in hybrid Benzin/Elektro",
  },
  { value: "cng-petrol", label: "Erdgas (CNG) / Benzin" },
  { value: "lpg-petrol", label: "Flüssiggas (LPG) / Benzin" },
  { value: "ethanol-petrol", label: "Bioethanol" },
  { value: "hydrogen", label: "Wasserstoff" },
] as const;

export const ColorEnum = [
  { value: "anthracite", label: "Anthrazit" },
  { value: "beige", label: "Beige" },
  { value: "black", label: "Schwarz" },
  { value: "blue", label: "Blau" },
  { value: "bordeaux", label: "Bordeaux" },
  { value: "brown", label: "Braun" },
  { value: "gold", label: "Gold" },
  { value: "gray", label: "Grau" },
  { value: "green", label: "Grün" },
  { value: "multicoloured", label: "Mehrfarbig" },
  { value: "orange", label: "Orange" },
  { value: "pink", label: "Rosa" },
  { value: "red", label: "Rot" },
  { value: "silver", label: "Silber" },
  { value: "turquoise", label: "Türkis" },
  { value: "violet", label: "Violett" },
  { value: "white", label: "Weiss" },
  { value: "yellow", label: "Gelb" },
  { value: "other", label: "Other" },
] as const;

export const VehicleConditionEnum = [
  { value: "new", label: "Neues Fahrzeug" },
  {
    value: "demonstration",
    label: "Vorführmodell",
  },
  { value: "pre-registered", label: "Neues Fahrzeug mit Tageszulassung" },
  { value: "used", label: "Occasion" },
  { value: "oldtimer", label: "Oldtimer" },
] as const;

export const WarrantyEnum = [
  { value: "from-delivery", label: "Ab Übernahme" },
  { value: "from-first-registration", label: "Ab 1. Inverkehrsetzung" },
  { value: "from-date", label: "Ab Datum" },
] as const;

export const EnergyLabelEnum = [
  { value: "a", label: "A" },
  { value: "b", label: "B" },
  { value: "c", label: "C" },
  { value: "d", label: "D" },
  { value: "e", label: "E" },
  { value: "f", label: "F" },
  { value: "g", label: "G" },
] as const;

export const EmissionStandardEnum = [
  { value: "euro-1", label: "Euro 1" },
  { value: "euro-2", label: "Euro 2" },
  { value: "euro-3", label: "Euro 3" },
  { value: "euro-4", label: "Euro 4" },
  { value: "euro-5", label: "Euro 5" },
  { value: "euro-5-plus", label: "Euro 5+" },
  { value: "euro-6", label: "Euro 6" },
  { value: "euro-6a", label: "Euro 6a" },
  { value: "euro-6b", label: "Euro 6b" },
  { value: "euro-6c", label: "Euro 6c" },
  { value: "euro-6d", label: "Euro 6d" },
  { value: "euro-6d-isc", label: "Euro 6d ISC" },
  { value: "euro-6d-isc-fcm", label: "Euro 6d ISC FCM" },
  { value: "euro-6d-temp", label: "Euro 6d Temp" },
  { value: "euro-6d-temp-evap", label: "Euro 6d Temp EVAP" },
  { value: "euro-6d-temp-evap-isc", label: "Euro 6d Temp EVAP ISC" },
  { value: "euro-6d-temp-isc", label: "Euro 6d Temp ISC" },
  { value: "euro-6e", label: "Euro 6e" },
] as const;

export const ChargingPlugTypeStandardEnum = [
  { value: "type-1", label: "Type 1" },
  { value: "type-2", label: "Type 2" },
] as const;

export const ChargingPlugTypeFastEnum = [
  { value: "ccs", label: "Ccs" },
  { value: "css-2", label: "Css-2" },
  { value: "chademo", label: "Chademo" },
  { value: "supercharger", label: "Supercharger" },
] as const;

export const BatteryOwnershipEnum = [
  {
    value: "battery-included",
    label: "Battery included in the purchase price",
  },
  {
    value: "battery-rent-required",
    label: "Battery requires an additional rent",
  },
] as const;

export const makes = [
  {
    label: "Top makes",
    items: [
      { value: "audi", label: "Audi" },
      { value: "bmw", label: "BMW" },
      { value: "ford", label: "Ford" },
      { value: "mercedes", label: "Mercedes-Benz" },
      { value: "opel", label: "Opel" },
      { value: "renault", label: "Renault" },
      { value: "volkswagen", label: "Volkswagen" },
    ],
  },
  {
    label: "Other makes",
    items: [
      { value: "9ff", label: "9ff" },
      { value: "abarth", label: "Abarth" },
      { value: "ac", label: "AC" },
      { value: "acm", label: "ACM" },
      { value: "acura", label: "Acura" },
      { value: "aerfal", label: "Aerfal" },
      { value: "aiways", label: "Aiways" },
      { value: "aixam", label: "Aixam" },
      { value: "alba-mobility", label: "Alba Mobility" },
      { value: "alfa-romeo", label: "Alfa Romeo" },
      { value: "alpina", label: "Alpina" },
      { value: "alpine", label: "Alpine" },
      { value: "amphicar", label: "Amphicar" },
      { value: "angelelli-automobili", label: "Angelelli Automobili" },
      { value: "ariel-motor", label: "Ariel Motor" },
      { value: "artega", label: "Artega" },
      { value: "aspark", label: "Aspark" },
      { value: "aspid", label: "Aspid" },
      { value: "aston-martin", label: "Aston Martin" },

      { value: "aurus", label: "Aurus" },
      { value: "austin", label: "Austin" },
      { value: "austin-healey", label: "Austin-Healey" },
      { value: "autobianchi", label: "Autobianchi" },
      { value: "baic", label: "BAIC" },
      { value: "baw", label: "BAW" },
      { value: "bedford", label: "Bedford" },
      { value: "bellier", label: "Bellier" },
      { value: "bentley", label: "Bentley" },
      { value: "bertone", label: "Bertone" },
      { value: "bestune", label: "Bestune" },

      { value: "boldmen", label: "Boldmen" },
      { value: "bollore", label: "Bolloré" },
      { value: "borgward", label: "Borgward" },
      { value: "brilliance", label: "Brilliance" },
      { value: "bristol", label: "Bristol" },
      { value: "brute", label: "Brute" },
      { value: "bugatti", label: "Bugatti" },
      { value: "buick", label: "Buick" },
      { value: "byd", label: "BYD" },
      { value: "cadillac", label: "Cadillac" },
      { value: "caravans-wohnm", label: "Caravans-Wohnm" },
      { value: "carver", label: "Carver" },
      { value: "casalini", label: "Casalini" },
      { value: "caterham", label: "Caterham" },
      { value: "cenntro", label: "Cenntro" },
      { value: "chamonix", label: "Chamonix" },
      { value: "changan", label: "Changan" },
      { value: "changhe", label: "Changhe" },
      { value: "chatenet", label: "Chatenet" },
      { value: "chery", label: "Chery" },
      { value: "chevrolet", label: "Chevrolet" },
      { value: "chrysler", label: "Chrysler" },
      { value: "cirelli", label: "Cirelli" },
      { value: "citroen", label: "Citroen" },
      { value: "cityel", label: "CityEL" },
      { value: "corvette", label: "Corvette" },
      { value: "cupra", label: "CUPRA" },
      { value: "dacia", label: "Dacia" },
      { value: "daewoo", label: "Daewoo" },
      { value: "daf", label: "DAF" },
      { value: "daihatsu", label: "Daihatsu" },
      { value: "daimler", label: "Daimler" },
      { value: "dallara", label: "Dallara" },
      { value: "dangel", label: "Dangel" },
      { value: "de-la-chapelle", label: "De la Chapelle" },
      { value: "de-tomaso", label: "De Tomaso" },
      { value: "delorean", label: "Delorean" },
      { value: "denza", label: "Denza" },
      { value: "devinci-cars", label: "Devinci Cars" },
      { value: "dfsk", label: "DFSK" },
      { value: "dodge", label: "Dodge" },
      { value: "dongfeng", label: "Dongfeng" },
      { value: "donkervoort", label: "Donkervoort" },
      { value: "dr-automobiles", label: "DR Automobiles" },
      { value: "ds-automobiles", label: "DS Automobiles" },
      { value: "dutton", label: "Dutton" },
      { value: "e-go", label: "e.GO" },
      { value: "ebro", label: "Ebro" },
      { value: "econelo", label: "Econelo" },
      { value: "edran", label: "Edran" },
      { value: "elaris", label: "Elaris" },
      { value: "embuggy", label: "Embuggy" },
      { value: "emc", label: "EMC" },
      { value: "estrima", label: "Estrima" },
      { value: "evetta", label: "Evetta" },
      { value: "evo", label: "EVO" },
      { value: "farizon", label: "Farizon" },
      { value: "ferrari", label: "Ferrari" },
      { value: "fiat", label: "Fiat" },
      { value: "fisker", label: "Fisker" },

      { value: "forthing", label: "Forthing" },
      { value: "foton", label: "Foton" },
      { value: "gac-gonow", label: "Gac Gonow" },
      { value: "galloper", label: "Galloper" },
      { value: "gappy", label: "Gappy" },
      { value: "gaz", label: "GAZ" },
      { value: "geely", label: "Geely" },
      { value: "gem", label: "GEM" },
      { value: "gemballa", label: "GEMBALLA" },
      { value: "genesis", label: "Genesis" },
      { value: "giana", label: "Giana" },
      { value: "gillet", label: "Gillet" },
      { value: "giotti-victoria", label: "Giotti Victoria" },
      { value: "gmc", label: "GMC" },
      { value: "goupil", label: "Goupil" },
      { value: "great-wall", label: "Great Wall" },
      { value: "grecav", label: "Grecav" },
      { value: "gta", label: "GTA" },
      { value: "gwm", label: "GWM" },
      { value: "haima", label: "Haima" },
      { value: "hamann", label: "Hamann" },
      { value: "haval", label: "Haval" },
      { value: "hiphi", label: "Hiphi" },
      { value: "holden", label: "Holden" },
      { value: "honda", label: "Honda" },
      { value: "hongqi", label: "Hongqi" },
      { value: "hummer", label: "HUMMER" },
      { value: "hurtan", label: "Hurtan" },
      { value: "hyundai", label: "Hyundai" },
      { value: "ich-x", label: "ICH-X" },
      { value: "ineos", label: "Ineos" },
      { value: "infiniti", label: "Infiniti" },
      { value: "innocenti", label: "Innocenti" },
      { value: "invicta", label: "Invicta" },
      { value: "iso-rivolta", label: "Iso Rivolta" },
      { value: "isuzu", label: "Isuzu" },
      { value: "iveco", label: "Iveco" },
      { value: "izh", label: "IZH" },
      { value: "jac", label: "JAC" },
      { value: "jaecoo", label: "Jaecoo" },
      { value: "jaguar", label: "Jaguar" },
      { value: "jeep", label: "Jeep" },
      { value: "jensen", label: "Jensen" },
      { value: "karma", label: "Karma" },
      { value: "kgm", label: "KGM" },
      { value: "kia", label: "Kia" },
      { value: "koenigsegg", label: "Koenigsegg" },
      { value: "ktm", label: "KTM" },
      { value: "lada", label: "Lada" },
      { value: "lamborghini", label: "Lamborghini" },
      { value: "lancia", label: "Lancia" },
      { value: "land-rover", label: "Land Rover" },
      { value: "ldv", label: "LDV" },
      { value: "leapmotor", label: "Leapmotor" },
      { value: "lee-group", label: "Lee Group" },
      { value: "levc", label: "LEVC" },
      { value: "lexus", label: "Lexus" },
      { value: "li", label: "Li" },
      { value: "lifan", label: "Lifan" },
      { value: "ligier", label: "Ligier" },
      { value: "lincoln", label: "Lincoln" },
      { value: "linzda", label: "Linzda" },
      { value: "livan", label: "Livan" },
      { value: "lorinser", label: "Lorinser" },
      { value: "lotus", label: "Lotus" },
      { value: "lucid", label: "Lucid" },
      { value: "lynk-co", label: "Lynk & Co" },
      { value: "m-ero", label: "M-Ero" },
      { value: "mahindra", label: "Mahindra" },
      { value: "man", label: "MAN" },
      { value: "mansory", label: "Mansory" },
      { value: "martin", label: "Martin" },
      { value: "martin-motors", label: "Martin Motors" },
      { value: "maserati", label: "Maserati" },
      { value: "matra", label: "Matra" },
      { value: "maxus", label: "Maxus" },
      { value: "maybach", label: "Maybach" },
      { value: "mazda", label: "Mazda" },
      { value: "mclaren", label: "McLaren" },
      { value: "mega", label: "Mega" },
      { value: "melex", label: "Melex" },

      { value: "mercury", label: "Mercury" },
      { value: "mg", label: "MG" },
      { value: "micro", label: "Micro" },
      { value: "microcar", label: "Microcar" },
      { value: "militem", label: "Militem" },
      { value: "minari", label: "Minari" },
      { value: "minauto", label: "Minauto" },
      { value: "mini", label: "MINI" },
      { value: "mitsubishi", label: "Mitsubishi" },
      { value: "mitsuoka", label: "Mitsuoka" },
      { value: "mobilize", label: "Mobilize" },
      { value: "morgan", label: "Morgan" },
      { value: "moskvich", label: "Moskvich" },
      { value: "mp-lafer", label: "MP Lafer" },
      { value: "mpm-motors", label: "MPM Motors" },
      { value: "nio", label: "NIO" },
      { value: "nissan", label: "Nissan" },
      { value: "nsu", label: "NSU" },
      { value: "oldsmobile", label: "Oldsmobile" },
      { value: "oldtimer", label: "Oldtimer" },
      { value: "omoda", label: "Omoda" },

      { value: "ora", label: "Ora" },
      { value: "pagani", label: "Pagani" },
      { value: "panther-westwinds", label: "Panther Westwinds" },
      { value: "peugeot", label: "Peugeot" },
      { value: "pgo", label: "PGO" },
      { value: "piaggio", label: "Piaggio" },
      { value: "plymouth", label: "Plymouth" },
      { value: "polestar", label: "Polestar" },
      { value: "pontiac", label: "Pontiac" },
      { value: "porsche", label: "Porsche" },
      { value: "proton", label: "Proton" },
      { value: "puch", label: "Puch" },
      { value: "ram", label: "RAM" },
      { value: "regis", label: "Regis" },
      { value: "reliant", label: "Reliant" },

      { value: "rivian", label: "Rivian" },
      { value: "rolls-royce", label: "Rolls-Royce" },
      { value: "rover", label: "Rover" },
      { value: "ruf", label: "Ruf" },
      { value: "saab", label: "Saab" },
      { value: "santana", label: "Santana" },
      { value: "seat", label: "SEAT" },
      { value: "segway", label: "Segway" },
      { value: "selvo", label: "Selvo" },
      { value: "seres", label: "Seres" },
      { value: "sevic", label: "Sevic" },
      { value: "sgs", label: "SGS" },
      { value: "shelby", label: "Shelby" },
      { value: "shuanghuan", label: "Shuanghuan" },
      { value: "silence", label: "Silence" },
      { value: "simplici", label: "Simplici" },
      { value: "singer", label: "Singer" },
      { value: "skoda", label: "Skoda" },
      { value: "skywell", label: "Skywell" },
      { value: "smart", label: "smart" },
      { value: "speedart", label: "SpeedArt" },
      { value: "sportequipe", label: "Sportequipe" },
      { value: "spyker", label: "Spyker" },
      { value: "ssangyong", label: "SsangYong" },
      { value: "stormborn", label: "Stormborn" },
      { value: "streetscooter", label: "StreetScooter" },
      { value: "studebaker", label: "Studebaker" },
      { value: "subaru", label: "Subaru" },
      { value: "suzuki", label: "Suzuki" },
      { value: "swm", label: "SWM" },
      { value: "talbot", label: "Talbot" },
      { value: "tasso", label: "Tasso" },
      { value: "tata", label: "Tata" },
      { value: "tazzari-ev", label: "Tazzari EV" },
      { value: "techart", label: "TECHART" },
      { value: "tesla", label: "Tesla" },
      { value: "tiger", label: "Tiger" },
      { value: "togg", label: "Togg" },
      { value: "town-life", label: "Town Life" },
      { value: "toyota", label: "Toyota" },
      { value: "trabant", label: "Trabant" },
      { value: "trailer-anhanger", label: "Trailer-Anhänger" },
      { value: "triumph", label: "Triumph" },
      { value: "trucks-lkw", label: "Trucks-Lkw" },
      { value: "tvr", label: "TVR" },
      { value: "uaz", label: "UAZ" },
      { value: "vanden-plas", label: "Vanden Plas" },
      { value: "vanderhall", label: "Vanderhall" },
      { value: "vaz", label: "VAZ" },
      { value: "vem", label: "VEM" },
      { value: "vinfast", label: "VinFast" },

      { value: "volvo", label: "Volvo" },
      { value: "voyah", label: "Voyah" },
      { value: "wartburg", label: "Wartburg" },
      { value: "weltmeister", label: "Weltmeister" },
      { value: "wenckstern", label: "Wenckstern" },
      { value: "westfield", label: "Westfield" },
      { value: "wey", label: "Wey" },
      { value: "wiesmann", label: "Wiesmann" },
      { value: "xbus", label: "XBus" },
      { value: "xev", label: "XEV" },
      { value: "xiaomi", label: "Xiaomi" },
      { value: "xpeng", label: "Xpeng" },
      { value: "zastava", label: "Zastava" },
      { value: "zaz", label: "ZAZ" },
      { value: "zeekr", label: "Zeekr" },
      { value: "zhidou", label: "Zhidou" },
      { value: "zotye", label: "Zotye" },
      { value: "others", label: "Others" },
    ],
  },
] as const;

export const models: Record<string, { value: string; label: string }[]> = {
  audi: [
    { value: "a1", label: "A1" },
    { value: "a3", label: "A3" },
    { value: "a4", label: "A4" },
    { value: "a6", label: "A6" },
    { value: "a8", label: "A8" },
    { value: "q3", label: "Q3" },
    { value: "q5", label: "Q5" },
    { value: "q7", label: "Q7" },
    { value: "q8", label: "Q8" },
    { value: "tt", label: "TT" },
    { value: "r8", label: "R8" },
    { value: "e-tron", label: "e-tron" },
  ],
  bmw: [
    { value: "1-series", label: "1 Series" },
    { value: "2-series", label: "2 Series" },
    { value: "3-series", label: "3 Series" },
    { value: "4-series", label: "4 Series" },
    { value: "5-series", label: "5 Series" },
    { value: "7-series", label: "7 Series" },
    { value: "x1", label: "X1" },
    { value: "x3", label: "X3" },
    { value: "x5", label: "X5" },
    { value: "x7", label: "X7" },
    { value: "i4", label: "i4" },
    { value: "i8", label: "i8" },
    { value: "ix", label: "iX" },
  ],
  mercedes: [
    { value: "a-class", label: "A-Class" },
    { value: "c-class", label: "C-Class" },
    { value: "e-class", label: "E-Class" },
    { value: "s-class", label: "S-Class" },
    { value: "gla", label: "GLA" },
    { value: "glb", label: "GLB" },
    { value: "glc", label: "GLC" },
    { value: "gle", label: "GLE" },
    { value: "gls", label: "GLS" },
    { value: "eqc", label: "EQC" },
    { value: "eqs", label: "EQS" },
  ],
  volkswagen: [
    { value: "golf", label: "Golf" },
    { value: "polo", label: "Polo" },
    { value: "passat", label: "Passat" },
    { value: "tiguan", label: "Tiguan" },
    { value: "touareg", label: "Touareg" },
    { value: "t-roc", label: "T-Roc" },
    { value: "arteon", label: "Arteon" },
    { value: "id3", label: "ID.3" },
    { value: "id4", label: "ID.4" },
  ],
  porsche: [
    { value: "911", label: "911" },
    { value: "718", label: "718" },
    { value: "cayenne", label: "Cayenne" },
    { value: "macan", label: "Macan" },
    { value: "panamera", label: "Panamera" },
    { value: "taycan", label: "Taycan" },
  ],
  ford: [
    { value: "fiesta", label: "Fiesta" },
    { value: "focus", label: "Focus" },
    { value: "mustang", label: "Mustang" },
    { value: "explorer", label: "Explorer" },
    { value: "f150", label: "F-150" },
    { value: "ranger", label: "Ranger" },
    { value: "edge", label: "Edge" },
  ],
  toyota: [
    { value: "corolla", label: "Corolla" },
    { value: "camry", label: "Camry" },
    { value: "rav4", label: "RAV4" },
    { value: "highlander", label: "Highlander" },
    { value: "prius", label: "Prius" },
    { value: "landcruiser", label: "Land Cruiser" },
    { value: "yaris", label: "Yaris" },
  ],
  honda: [
    { value: "civic", label: "Civic" },
    { value: "accord", label: "Accord" },
    { value: "crv", label: "CR-V" },
    { value: "hrv", label: "HR-V" },
    { value: "pilot", label: "Pilot" },
    { value: "fit", label: "Fit" },
  ],
  nissan: [
    { value: "altima", label: "Altima" },
    { value: "maxima", label: "Maxima" },
    { value: "sentra", label: "Sentra" },
    { value: "rogue", label: "Rogue" },
    { value: "murano", label: "Murano" },
    { value: "pathfinder", label: "Pathfinder" },
    { value: "leaf", label: "Leaf" },
  ],
  hyundai: [
    { value: "elantra", label: "Elantra" },
    { value: "sonata", label: "Sonata" },
    { value: "tucson", label: "Tucson" },
    { value: "santa-fe", label: "Santa Fe" },
    { value: "kona", label: "Kona" },
    { value: "ioniq", label: "Ioniq" },
  ],
} as const;

export const prices = [
  { value: "500", label: "€500" },
  { value: "1000", label: "€1,000" },
  { value: "1500", label: "€1,500" },
  { value: "2000", label: "€2,000" },
  { value: "2500", label: "€2,500" },
  { value: "3000", label: "€3,000" },
  { value: "4000", label: "€4,000" },
  { value: "5000", label: "€5,000" },
  { value: "6000", label: "€6,000" },
  { value: "7000", label: "€7,000" },
  { value: "8000", label: "€8,000" },
  { value: "9000", label: "€9,000" },
  { value: "10000", label: "€10,000" },
  { value: "12500", label: "€12,500" },
  { value: "15000", label: "€15,000" },
  { value: "17500", label: "€17,500" },
  { value: "20000", label: "€20,000" },
  { value: "25000", label: "€25,000" },
  { value: "30000", label: "€30,000" },
  { value: "40000", label: "€40,000" },
  { value: "50000", label: "€50,000" },
  { value: "75000", label: "€75,000" },
  { value: "100000", label: "€100,000" },
] as const;

export const countries = [
  { value: "europe", label: "Europe", flag: "🇪🇺" },
  { value: "austria", label: "Austria", flag: "🇦🇹" },
  { value: "belgium", label: "Belgium", flag: "🇧🇪" },
  { value: "germany", label: "Germany", flag: "🇩🇪" },
  { value: "spain", label: "Spain", flag: "🇪🇸" },
  { value: "france", label: "France", flag: "🇫🇷" },
  { value: "italy", label: "Italy", flag: "🇮🇹" },
  { value: "luxembourg", label: "Luxembourg", flag: "🇱🇺" },
  { value: "netherlands", label: "Netherlands", flag: "🇳🇱" },
] as const;

export const EquipmentEnum = [
  { value: "360-camera", label: "360°-Kamera" },
  { value: "abs", label: "ABS" },
  { value: "adaptive-headlights", label: "Adaptive Scheinwerfer" },
  { value: "adaptive-cruise-control", label: "Adaptiver Tempomat" },
  { value: "alarm-system", label: "Alarmanlage" },
  { value: "alloy-wheels", label: "Aluminiumfelgen" },
  { value: "android-auto", label: "Android Auto" },
  { value: "tow-hitch", label: "Anhängerkupplung" },
  { value: "tow-hitch-removable", label: "Anhängerkupplung abnehmbar" },
  { value: "tow-hitch-swiveling", label: "Anhängerkupplung schwenkbar" },
  { value: "tow-hitch-fixed", label: "Anhängerkupplung fix" },
  { value: "apple-carplay", label: "Apple CarPlay" },
  { value: "heated-seats", label: "Beheizbare Sitze" },
  { value: "ventilated-seats", label: "Belüftete Sitze" },
  { value: "bluetooth", label: "Bluetooth-Schnittstelle" },
  { value: "brake-assist", label: "Bremsassistent" },
  { value: "chrome-elements", label: "Chromelemente" },
  { value: "dab-radio", label: "DAB-Radio" },
  { value: "anti-theft", label: "Diebstahlsicherung" },
  { value: "differential-lock", label: "Differenzialsperre" },
  { value: "electric-windows", label: "Elektrische Fensterheber" },
  { value: "electric-tailgate", label: "Elektrische Heckklappe" },
  { value: "electric-seat-adjustment", label: "Elektrische Sitzverstellung" },
  { value: "gull-wing-doors", label: "Flügeltüren" },
  { value: "hands-free", label: "Freisprechanlage" },
  { value: "floor", label: "Fussboden" },
  { value: "roof-rack", label: "Gepäckträger" },
  { value: "hardtop", label: "Hardtop" },
  { value: "head-up-display", label: "Head-up-Display" },
  { value: "custom-exhaust", label: "Individuelle Auspuffanlage" },
  { value: "isofix", label: "Isofix" },
  { value: "air-conditioning", label: "Klimaanlage" },
  { value: "automatic-climate-control", label: "Automatische Klimaanlage" },
  { value: "trunk", label: "Koffer" },
  { value: "speakers", label: "Lautsprecher" },
  { value: "air-suspension", label: "Luftfederung" },
  { value: "navigation-system", label: "Navigationssystem" },
  { value: "navigation", label: "Navigation" },
  { value: "portable-navigation", label: "Tragbares Navigationssystem" },
  { value: "panoramic-roof", label: "Panoramadach" },
  { value: "parking-assist", label: "Parkhilfe" },
  { value: "parking-sensors-rear", label: "Parksensoren hinten" },
  { value: "parking-sensors-front", label: "Parksensoren vorne" },
  { value: "backrest-protection", label: "Rückenlehnenschutz" },
  { value: "backup-camera", label: "Rückfahrkamera" },
  { value: "headlights", label: "Scheinwerfer" },
  { value: "laser-headlights", label: "Laser Scheinwerfer" },
  { value: "led-headlights", label: "LED-Scheinwerfer" },
  { value: "xenon-headlights", label: "Xenonscheinwerfer" },
  { value: "sunroof", label: "Schiebedach" },
  { value: "sliding-door", label: "Schiebetür" },
  { value: "keyless-entry-start", label: "Schlüsselloser Zugang/Start" },
  { value: "fast-charging", label: "Schnellladen" },
  { value: "seat-covers", label: "Sitzbezüge" },
  { value: "alcantara", label: "Alcantara" },
  { value: "fabric-seats", label: "Stoffsitze" },
  { value: "leather", label: "Leder" },
  { value: "partial-leather-seats", label: "Teil-Ledersitze" },
  { value: "special-paint", label: "Sonderlackierung" },
  { value: "sport-seats", label: "Sportsitze" },
  { value: "lane-keep-assist", label: "Spurhalteassistent" },
  { value: "esp", label: "Stabilitätskontrolle (ESP)" },
  { value: "auxiliary-heating", label: "Standheizung" },
  { value: "start-stop-system", label: "Start-Stopp-System" },
  { value: "cruise-control", label: "Tempomat" },
  { value: "blind-spot-assist", label: "Totwinkel-Assistent" },
  { value: "reinforced-suspension", label: "Verstärkte Federung" },
  { value: "additional-instruments", label: "Zusätzliche Instrumente" },
] as const;

export const ExtrasEnum = [
  { value: "8-tyres", label: "8-fach bereift" },
  { value: "accessible-for-disabled", label: "Behindertengerecht" },
  { value: "accident-vehicle", label: "Unfallfahrzeug" },
  { value: "race-car", label: "Rennwagen" },
  { value: "tuning", label: "Tuning" },
] as const;
