export const pricingTiers = [
  {
    name: "Basic 5",
    price: "180.–",
    period: "/ monat",
    description: "Ideal für kleinere Bestände.",
    features: [
      { name: "Bis zu 5 Inserate", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
  {
    name: "Basic 10",
    price: "280.–",
    period: "/ monat",
    description: "Perfekt für wachsende Händler.",
    features: [
      { name: "Bis zu 10 Inserate", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: true,
  },
  {
    name: "Basic 15",
    price: "325.–",
    period: "/ monat",
    description: "Für etablierte Händler.",
    features: [
      { name: "Bis zu 15 Inserate", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
  {
    name: "Basic 25",
    price: "408.–",
    period: "/ monat",
    description: "Für Händler mit höherem Volumen.",
    features: [
      { name: "Bis zu 25 Inserate", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
];
