export const pricingTiers = [
  {
    name: "Starter",
    price: "10 CHF",
    period: "/ monat",
    description: "Ideal für Einsteiger mit wenigen Fahrzeugen.",
    features: [
      { name: "Bis zu 5 Inserate", included: true },
      { name: "Standard-Sichtbarkeit", included: true },
      { name: "Basis-Support", included: true },
      { name: "Top-Platzierung", included: false },
      { name: "API-Anbindung", included: false },
    ],
    buttonText: "Kostenlos starten",
    popular: false,
  },
  {
    name: "Basic",
    price: "15 CHF",
    period: "/ monat",
    description: "Perfekt für kleine und wachsende Händler.",
    features: [
      { name: "Bis zu 20 Inserate", included: true },
      { name: "Erhöhte Sichtbarkeit", included: true },
      { name: "Prioritäts-Support", included: true },
      { name: "Top-Platzierung", included: false },
      { name: "API-Anbindung", included: false },
    ],
    buttonText: "Basic wählen",
    popular: false,
  },
  {
    name: "Pro",
    price: "20 CHF",
    period: "/ monat",
    description: "Für etablierte Händler mit mittlerem Volumen.",
    features: [
      { name: "Unbegrenzte Inserate", included: true },
      { name: "Maximale Sichtbarkeit", included: true },
      { name: "Persönlicher Ansprechpartner", included: true },
      { name: "10 Top-Platzierungen", included: true },
      { name: "API-Anbindung", included: false },
    ],
    buttonText: "Pro wählen",
    popular: false,
  },
  {
    name: "Enterprise",
    price: "25 CHF",
    period: "/ monat",
    description: "Massgeschneiderte Lösungen für grosse Autohäuser.",
    features: [
      { name: "Unbegrenzte Inserate", included: true },
      { name: "Maximale Sichtbarkeit", included: true },
      { name: "Persönlicher Ansprechpartner", included: true },
      { name: "Unbegrenzte Top-Platzierungen", included: true },
      { name: "API-Anbindung", included: true },
    ],
    buttonText: "Kontakt aufnehmen",
    popular: true,
  },
];
