export const pricingTiers = [
  {
    name: "Bronze",
    price: "180.–",
    period: "/ monat",
    description: "Ideal für kleinere Bestände.",
    features: [
      { name: "Bis zu 5 Fahrzeuge", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
  {
    name: "Silver",
    price: "280.–",
    period: "/ monat",
    description: "Perfekt für wachsende Händler.",
    features: [
      { name: "Bis zu 10 Fahrzeuge", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
  {
    name: "Gold",
    price: "325.–",
    period: "/ monat",
    description: "Für etablierte Händler.",
    features: [
      { name: "Bis zu 15 Fahrzeuge", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: true,
  },
  {
    name: "Diamond",
    price: "408.–",
    period: "/ monat",
    description: "Für Händler mit höherem Volumen.",
    features: [
      { name: "Bis zu 25 Fahrzeuge", included: true },
      { name: "Volle Sichtbarkeit", included: true },
      { name: "Persönlicher Support", included: true },
      { name: "Keine versteckten Kosten", included: true },
      { name: "Laufzeit flexibel", included: true },
    ],
    buttonText: "Paket wählen",
    popular: false,
  },
];
