[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx turbo run build --filter=$APP_NAME"]

[start]
cmd = "node_modules/.bin/prisma migrate deploy --schema=packages/database/prisma/schema.prisma && node_modules/.bin/next start $APP_DIR -p $PORT"
