export const swissCities = [
  "Aarau",
  "Aclens",
  "Agiez",
  "Aire-la-Ville",
  "Allaman",
  "Anières",
  "Apples",
  "Arnex-sur-Orbe",
  "Athenaz (Avusy)",
  "Aubonne",
  "Autavaux - Montbrelloz - Forel",
  "Avenches - Oleyres",
  "Avully",
  "Ballaigues",
  "Ballens",
  "Basel",
  "Bassins",
  "Baulmes",
  "Bavois",
  "Bellevue",
  "Belmont-sur-Lausanne",
  "Bercher",
  "Bern",
  "Bernex",
  "Berolle",
  "Bioley-Orjulaz - Bettens - Assens",
  "Bière",
  "Bofflens",
  "Bonvillars",
  "Borex - Arnex-sur-Nyon",
  "Bougy-Villars",
  "Bournens",
  "Boussens",
  "Bremblens",
  "Bretonnières",
  "Buchillon",
  "Bursinel - Dully",
  "Bursins",
  "Burtigny - Begnins",
  "Bussigny-près-Lausanne",
  "Bussy-Chardonney",
  "Bussy-sur-Moudon",
  "Carrouge",
  "Cartigny",
  "Chabrey",
  "Chambésy",
  "Champagne",
  "Champtauroz",
  "Chancy",
  "Chanéaz",
  "Chapelle (Broye) - Sassel",
  "Chavannes-de-Bogis - Bogis-Bossey",
  "Chavannes-le-Chêne - Chêne-Pâquier",
  "Chavannes-près-Renens",
  "Chavannes-sur-Moudon",
  "Chavornay",
  "Cheiry",
  "Chenaux - Grandvaux - Aran",
  "Cheseaux Polyval",
  "Cheseaux-sur-Lausanne",
  "Chevilly",
  "Chevroux",
  "Cheyres",
  "Choulex",
  "Chur",
  "Châbles",
  "Châtelaine - Le Lignon - Aïre",
  "Châtonnaye",
  "Chéserex",
  "Chêne-Bougeries",
  "Chêne-Bourg",
  "Clarmont",
  "Clavaleyres - Faoug",
  "Cointrin",
  "Collex",
  "Collonge-Bellerive",
  "Cologny",
  "Colombier",
  "Combremont-le-Grand",
  "Combremont-le-Petit",
  "Commugny",
  "Conches",
  "Concise - Corcelles-près-Concise",
  "Confignon",
  "Constantine - Montmagny",
  "Coppet",
  "Corcelles-le-Jorat",
  "Corcelles-près-Payerne",
  "Corcelles-sur-Chavornay",
  "Corsier",
  "Cottens",
  "Crans-près-Céligny",
  "Crassier",
  "Crissier",
  "Cronay",
  "Croy",
  "Cuarny - Villars-Epeney",
  "Cudrefin",
  "Cugy",
  "Cugy - Bretigny-sur-Morrens",
  "Curtilles",
  "Céligny",
  "Daillens",
  "Dardagny - La Plaine",
  "Delley",
  "Denens",
  "Dizy - Senarclens - Allens - Cossonay-Ville",
  "Domdidier",
  "Dompierre",
  "Donatyre",
  "Donneloye - Gossens - Mézery-près-Donneloye - Bioley-Magnoux",
  "Duillier",
  "Echallens - St-Barthélemy - Villars-le-Terroir",
  "Echandens - Denges",
  "Echichens",
  "Eclagnens - Goumoens-la-Ville - Goumoens-le-Jux",
  "Eclépens",
  "Ecublens",
  "Epalinges",
  "Epautheyres - Essertines-sur-Yverdon",
  "Ependes",
  "Epesses",
  "Essert-Pittet",
  "Essert-sous-Champvent - Champvent - Villars-sous-Champvent",
  "Essertes",
  "Essertines-sur-Rolle",
  "Etagnières",
  "Etoy",
  "Eysins",
  "Ferlens",
  "Ferreyres",
  "Fey",
  "Fiez",
  "Font - Châtillon",
  "Forel (Lavaux)",
  "Forel-sur-Lucens - Cremin",
  "Founex",
  "Frasses - Montet (Broye) - Vesin",
  "Froideville",
  "Féchy",
  "Fétigny",
  "Genolier",
  "Genthod",
  "Genève",
  "Giez",
  "Gilly",
  "Gimel - St-George",
  "Gingins",
  "Givrins",
  "Gland",
  "Gletterens",
  "Gollion",
  "Grancy",
  "Grand-Lancy",
  "Grandcour",
  "Grandevent - Fontaines-sur-Grandson",
  "Grandson",
  "Granges-de-Vesin - Aumont",
  "Granges-près-Marnand",
  "Grens - Signy",
  "Gressy - Belmont-sur-Yverdon",
  "Gy",
  "Hermance",
  "Hermenches - Rossenges",
  "Jouxtens-Mézery - Prilly",
  "Juriens",
  "Jussy",
  "L'Abbaye",
  "L'Auberson - La Vraconnaz",
  "La Chaux (Cossonay)",
  "La Conversion",
  "La Croix (Lutry)",
  "La Croix-de-Rozon",
  "La Cure",
  "La Praz - Chavannes-le-Veyron - Villars-Bozon - La Coudre - Cuarnens - Moiry - Mont-la-Ville - Mauraz - L'Isle",
  "La Rippe",
  "La Russille - Les Clées",
  "La Sarraz",
  "Laconnex",
  "Lausanne",
  "Lavigny",
  "Le Brassus",
  "Le Château-de-Ste-Croix - La Sagne (Ste-Croix) - Ste-Croix",
  "Le Grand-Saconnex",
  "Le Lieu",
  "Le Mont-sur-Lausanne",
  "Le Muids - Arzier",
  "Le Pont",
  "Le Sentier - Le Solliat",
  "Les Acacias - Carouge",
  "Les Avanchets",
  "Les Bioux",
  "Les Charbonnières",
  "Les Cullayes",
  "Les Monts-de-Pully",
  "Les Rasses",
  "Lignerolle",
  "Lonay",
  "Longirod - Le Vaud - Marchissy",
  "Luins - Vinzel",
  "Lully",
  "Lussery-Villars",
  "Lussy-sur-Morges",
  "Lutry",
  "Luzern",
  "Marnand",
  "Martherenges - Chapelle-sur-Moudon - Boulens - Peyres-Possens",
  "Mathod",
  "Mauborget - Bullet",
  "Meinier",
  "Mex",
  "Meyrin",
  "Mies - Tannay",
  "Mollens",
  "Molondin - Démoret",
  "Monnaz",
  "Mont-sur-Rolle",
  "Montagny-Chamard",
  "Montagny-près-Yverdon",
  "Montcherand",
  "Montherod - Pizy",
  "Montpreveyres",
  "Montricher",
  "Morges",
  "Morrens",
  "Murist",
  "Ménières",
  "Mézières",
  "Neuchâtel",
  "Novalles - Vugelles-La Mothe",
  "Nuvilly",
  "Nyon",
  "Ogens",
  "Onex - Petit-Lancy",
  "Onnens",
  "Oppens",
  "Orbe",
  "Orges",
  "Orient",
  "Orny",
  "Orzens",
  "Oulens-sous-Echallens",
  "Oulens-sur-Lucens - Lucens",
  "Pailly",
  "Pampigny",
  "Paudex",
  "Payerne",
  "Peney-le-Jorat",
  "Penthalaz",
  "Penthaz",
  "Penthéréaz",
  "Perly",
  "Perroy",
  "Plan-les-Ouates",
  "Poliez-le-Grand - Bottens - Poliez-Pittet - Naz - Dommartin - Montaubion-Chardonney",
  "Pompaples",
  "Pomy",
  "Portalban",
  "Prahins",
  "Prangins",
  "Premier",
  "Presinge",
  "Provence - Mutrux",
  "Préverenges",
  "Prévondavaux - Thierrens - St-Cierges - Correvon - Denezy",
  "Puidoux",
  "Pully",
  "Puplinge",
  "Rances",
  "Renens",
  "Reverolle",
  "Riex",
  "Rivaz - St-Saphorin (Lavaux) - Chexbres",
  "Romainmôtier",
  "Romanel-sur-Lausanne",
  "Romanel-sur-Morges",
  "Ropraz",
  "Rovray",
  "Rueyres",
  "Rueyres-les-Prés",
  "Russin",
  "Salavaux - Cotterd - Bellerive",
  "Satigny",
  "Saubraz",
  "Savigny - Mollie-Margot",
  "Seigneux - Henniez",
  "Seiry - Bollion - Lully - Estavayer-le-Lac",
  "Sergey - L'Abergement",
  "Servion",
  "Soral",
  "Sottens",
  "St-Aubin - Les Friques",
  "St-Cergue",
  "St-Livres",
  "St-Oyens",
  "St-Prex",
  "St-Saphorin-sur-Morges",
  "St-Sulpice",
  "St. Gallen",
  "Suchy",
  "Sugnens",
  "Sullens",
  "Surpierre - Praratoud",
  "Suscévaz",
  "Syens - Moudon",
  "Sédeilles - Rossens",
  "Sévaz - Morens - Bussy",
  "Sévery",
  "Tartegnin - Rolle",
  "Thônex",
  "Tolochenaz",
  "Trey",
  "Treycovagnes - Chamblon",
  "Treytorrens (Payerne)",
  "Troinex",
  "Trélex",
  "Ursins - Valeyres-sous-Ursins",
  "Valeyres-sous-Montagny",
  "Valeyres-sous-Rances",
  "Vallamand",
  "Vallon - Missy",
  "Vallorbe",
  "Vandoeuvres",
  "Vaugondry - Fontanezier - Romairon - Villars-Burquin",
  "Vaulion",
  "Vaux-sur-Morges",
  "Vernier",
  "Vers-chez-Perrin",
  "Versoix - Chavannes-des-Bois",
  "Vessy",
  "Veyrier",
  "Vich - Coinsins",
  "Villarepos",
  "Villars-Mendraz",
  "Villars-Ste-Croix",
  "Villars-Tiercelin",
  "Villars-le-Comte - Neyruz-sur-Moudon",
  "Villars-le-Grand",
  "Villars-sous-Yens",
  "Villarzel",
  "Villeneuve",
  "Villette (Lavaux) - Cully",
  "Vuarrens",
  "Vucherens",
  "Vufflens-la-Ville",
  "Vufflens-le-Château - Chigny",
  "Vuissens",
  "Vuiteboeuf",
  "Vulliens",
  "Vullierens",
  "Vésenaz",
  "Yens",
  "Yverdon-les-Bains",
  "Yverdon-les-Bains - Cheseaux-Noréaz",
  "Yvonand",
  "Zürich",
];
