export const camperMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "ADRIA", label: "Adria" },
      { value: "BURSTNER", label: "Bürstner" },
      { value: "CARADO", label: "Carado" },
      { value: "DETHLEFFS", label: "Dethleffs" },
      { value: "FENDT", label: "Fendt" },
      { value: "HOBBY", label: "Hobby" },
      { value: "HYMER", label: "Hymer" },
      { value: "KNAUS", label: "Knaus" },
      { value: "LMC", label: "LMC" },
      { value: "SUNLIGHT", label: "Sunlight" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "ACTION_MOBIL", label: "Action Mobil" },
      { value: "ADVENTURER", label: "Adventurer" },
      { value: "AERO_ONE", label: "Aero One" },
      { value: "AERO_PLAST", label: "Aero Plast" },
      { value: "AHORN", label: "Ahorn" },
      { value: "AIRSTREAM", label: "Airstream" },
      { value: "ARCA", label: "Arca" },
      { value: "AUTO_SLEEPERS", label: "Auto-Sleepers" },
      { value: "AUTOSTAR", label: "Autostar" },
      { value: "AVANTI", label: "Avanti" },
      { value: "AZALAI", label: "Azalai" },
      { value: "BANTAM", label: "Bantam" },
      { value: "BASKENT_KARAVAN", label: "Baskent Karavan" },
      { value: "BAVARIA", label: "Bavaria" },
      { value: "BAVARIACAMP", label: "Bavariacamp" },
      { value: "BEAUER", label: "Beauer" },
      { value: "BEDFORD", label: "Bedford" },
      { value: "BENIMAR", label: "Benimar" },
      { value: "BERKSHIRE", label: "Berkshire" },
      { value: "BILLYS", label: "Billys" },
      { value: "BIMOBIL", label: "Bimobil" },
      { value: "BISON", label: "Bison" },
      { value: "BLUCAMP", label: "Blucamp" },
      { value: "BOCKLET", label: "Bocklet" },
      { value: "BRAVIA", label: "Bravia" },
      { value: "BREMACH", label: "Bremach" },
      { value: "BUCHER", label: "Bucher" },
      { value: "BUNKERVAN", label: "Bunkervan" },
      { value: "BUROW", label: "Burow" },
      { value: "CALLAU", label: "Callau" },
      { value: "CAMP_LET", label: "Camp-Let" },
      { value: "CAMPPASS", label: "Camppass" },
      { value: "CAPRA_CAMPER", label: "Capra Camper" },
      { value: "CARAVELAIR", label: "Caravelair" },
      { value: "CARETTA", label: "Caretta" },
      { value: "CARTHAGO", label: "Carthago" },
      { value: "CHALLENGER", label: "Challenger" },
      { value: "CHAUSSON", label: "Chausson" },
      { value: "CHEVROLET", label: "Chevrolet" },
      { value: "CI_CARAVANSINTERNATIONAL", label: "CI Caravansinternational" },
      { value: "CITROEN", label: "Citroen" },
      { value: "CLEVER_VANS", label: "Clever Vans" },
      { value: "COACHMEN", label: "Coachmen" },
      { value: "COMANCHE", label: "Comanche" },
      { value: "CONCORDE", label: "Concorde" },
      { value: "CONQUEROR_COMPANION", label: "Conqueror Companion" },
      { value: "CONSTRUCTAM", label: "Constructam" },
      { value: "CRAMER_TECHNIK", label: "Cramer Technik" },
      { value: "CRAWLER", label: "Crawler" },
      { value: "CRISTAL", label: "Cristal" },
      { value: "CROSSCAMP", label: "Crosscamp" },
      { value: "CROSSROAD", label: "Crossroad" },
      { value: "CS_REISEMOBILE", label: "CS-Reisemobile" },
      { value: "DACIA", label: "Dacia" },
      { value: "DAF", label: "DAF" },
      { value: "DAIMLER", label: "Daimler" },
      { value: "DALTEC", label: "Daltec" },
      { value: "DAMON", label: "Damon" },
      { value: "DEHLER", label: "Dehler" },
      { value: "DODGE", label: "Dodge" },
      { value: "DOVRA", label: "Dovra" },
      { value: "DREAMER", label: "Dreamer" },
      { value: "DUE_ERRE", label: "Due Erre" },
      { value: "DUSS", label: "Duss" },
      { value: "DUX", label: "Dux" },
      { value: "EAGLE_RIDGE", label: "Eagle Ridge" },
      { value: "EASY_CARAVANNING", label: "Easy Caravanning" },
      { value: "EIFFELLAND", label: "Eiffelland" },
      { value: "ELNAGH", label: "Elnagh" },
      { value: "ERBA_KARAVAN", label: "Erba Karavan" },
      { value: "ERIBA", label: "Eriba" },
      { value: "ESTEREL", label: "Esterel" },
      { value: "ETRUSCO", label: "Etrusco" },
      { value: "EURA_MOBIL", label: "Eura Mobil" },
      { value: "EUROLINER_WORKHORSE", label: "Euroliner / Workhorse" },
      { value: "EVERGREEN", label: "Evergreen" },
      { value: "F_KON", label: "F-Kon" },
      { value: "FAMA_SCHMIDT", label: "Fama Schmidt" },
      { value: "FFB", label: "FFB" },
      { value: "FIAT", label: "Fiat" },
      { value: "FLAGSTAFF", label: "Flagstaff" },
      { value: "FLEETWOOD", label: "Fleetwood" },
      { value: "FLEURETTE", label: "Fleurette" },
      { value: "FONT_VENDOME", label: "Font Vendome" },
      { value: "FORD", label: "Ford" },
      { value: "FORREST_RIVER", label: "Forrest River" },
      { value: "FORSTER", label: "Forster" },
      { value: "FOUR_WINDS_INTERNATIONAL", label: "Four Winds International" },
      { value: "FRANKIA", label: "Frankia" },
      { value: "FREIGHTLINER", label: "Freightliner" },
      { value: "GAZ", label: "GAZ" },
      { value: "GEOCAMPER", label: "Geocamper" },
      { value: "GIOTTILINE", label: "Giottiline" },
      { value: "GLENDALE_RV", label: "Glendale RV" },
      { value: "GLOBE_TRAVELLER", label: "Globe-Traveller" },
      { value: "GLOBECAR", label: "Globecar" },
      { value: "GMC", label: "GMC" },
      { value: "GRAND_DESIGN", label: "Grand Design" },
      { value: "HANROAD", label: "Hanroad" },
      { value: "HEHN_MOBIL", label: "Hehn Mobil" },
      { value: "HEROCAMPER", label: "Herocamper" },
      { value: "HOLIDAY_RAMBLER", label: "Holiday Rambler" },
      { value: "HOME_CAR", label: "Home-Car" },
      { value: "HOTOMOBIL", label: "Hotomobil" },
      { value: "HUNTER_NATURE", label: "Hunter Nature" },
      { value: "HYUNDAI", label: "Hyundai" },
      { value: "ILUSION", label: "Ilusion" },
      { value: "IMPRESSION", label: "Impression" },
      { value: "INTERNATIONAL", label: "International" },
      { value: "ISUZU", label: "Isuzu" },
      { value: "ITINEO", label: "Itineo" },
      { value: "IVECO", label: "Iveco" },
      { value: "JAMES_COOK", label: "James Cook" },
      { value: "JEEP", label: "Jeep" },
      { value: "JOINT", label: "Joint" },
      { value: "KABE", label: "Kabe" },
      { value: "KAISER", label: "Kaiser" },
      { value: "KARMANN", label: "Karmann" },
      { value: "KEMPF", label: "Kempf" },
      { value: "KENTUCKY", label: "Kentucky" },
      { value: "LA_STRADA", label: "La Strada" },
      { value: "LAIKA", label: "Laika" },
      { value: "LAND_ROVER", label: "Land Rover" },
      { value: "LANDER", label: "Lander" },
      { value: "LAPP_EXPEDITIONSTRAILER", label: "Lapp Expeditionstrailer" },
      { value: "LE_VOYAGEUR", label: "Le Voyageur" },
      { value: "LSC", label: "LSC" },
      { value: "LUME", label: "Lume" },
      { value: "LUME_TRAVELER", label: "Lume Traveler" },
      { value: "MALIBU", label: "Malibu" },
      { value: "MAN", label: "MAN" },
      { value: "MARTIN", label: "Martin" },
      { value: "MAURER", label: "Maurer" },
      { value: "MAXUS", label: "Maxus" },
      { value: "MAZDA", label: "Mazda" },
      { value: "MCLOUIS", label: "McLouis" },
      { value: "MEGA_MOBIL", label: "Mega Mobil" },
      { value: "MERCEDES_BENZ", label: "Mercedes-Benz" },
      { value: "METALIAN", label: "Metalian" },
      { value: "MILLER", label: "Miller" },
      { value: "MINI_FREESTYLE", label: "Mini-Freestyle" },
      { value: "MINIATOURING", label: "Miniatouring" },
      { value: "MINK", label: "Mink" },
      { value: "MIRAGE", label: "Mirage" },
      { value: "MITSUBISHI", label: "Mitsubishi" },
      { value: "MKP", label: "MKP" },
      { value: "MOBILVETTA", label: "Mobilvetta" },
      { value: "MONACO", label: "Monaco" },
      { value: "MONCAYO", label: "Moncayo" },
      { value: "MOOBLEHOUSE", label: "Mooblehouse" },
      { value: "MOOVEO", label: "Mooveo" },
      { value: "MORELO", label: "Morelo" },
      { value: "NAGETUSCH", label: "Nagetusch" },
      { value: "NEWMAR", label: "Newmar" },
      { value: "NIESMANN_+_BISCHOFF", label: "Niesmann + Bischoff" },
      { value: "NIEWIADOW", label: "Niewiadow" },
      { value: "NISSAN", label: "Nissan" },
      { value: "NOBELART", label: "Nobelart" },
      { value: "NORDLIGHT_CAMPER", label: "Nordlight Camper" },
      { value: "NOTIN", label: "Notin" },
      { value: "OPEL", label: "Opel" },
      { value: "ORANGECAMP", label: "Orangecamp" },
      { value: "ORMO", label: "Ormo" },
      { value: "PALOMINO", label: "Palomino" },
      { value: "PANAMA", label: "Panama" },
      { value: "PAPILLON", label: "Papillon" },
      { value: "PEUGEOT", label: "Peugeot" },
      { value: "PHOENIX", label: "Phoenix" },
      { value: "PILOTE", label: "Pilote" },
      { value: "PLA", label: "PLA" },
      { value: "POLAR", label: "Polar" },
      { value: "POSSL", label: "Pössl" },
      { value: "PROCAMP", label: "Procamp" },
      { value: "PUCH", label: "Puch" },
      { value: "RANDGER", label: "Randger" },
      { value: "RAPIDO", label: "Rapido" },
      { value: "RAUSSCHWARMER", label: "Rausschwärmer" },
      { value: "REFLECTION", label: "Reflection" },
      { value: "RENAULT", label: "Renault" },
      { value: "REXHALL", label: "Rexhall" },
      { value: "RHON_CAMP", label: "Rhön Camp" },
      { value: "RIMOR", label: "Rimor" },
      { value: "RIVIERA", label: "Riviera" },
      { value: "RL_MOBILE", label: "RL-Mobile" },
      { value: "RMB", label: "RMB" },
      { value: "ROADCAR", label: "Roadcar" },
      { value: "ROBEL_MOBIL", label: "Robel Mobil" },
      { value: "ROBETA", label: "Robeta" },
      { value: "ROCKET_CARAVANS", label: "Rocket Caravans" },
      { value: "ROCKWOOD", label: "Rockwood" },
      { value: "ROLLER_TEAM", label: "Roller Team" },
      { value: "SALY", label: "Saly" },
      { value: "SAURER", label: "Saurer" },
      { value: "SCANIA", label: "Scania" },
      { value: "SCANVOGN", label: "Scanvogn" },
      { value: "SCHWABENMOBIL", label: "Schwabenmobil" },
      { value: "SEA", label: "Sea" },
      { value: "SEALANDER", label: "Sealander" },
      { value: "SETRA", label: "Setra" },
      { value: "SILVER", label: "Silver" },
      { value: "SKYLINE", label: "Skyline" },
      { value: "SOLIFER", label: "Solifer" },
      { value: "SPRITE", label: "Sprite" },
      { value: "STARCRAFT", label: "Starcraft" },
      { value: "STARLINER", label: "Starliner" },
      { value: "STERCKEMAN", label: "Sterckeman" },
      { value: "STEYR", label: "Steyr" },
      { value: "STYLEVAN", label: "Stylevan" },
      { value: "SUN_LIVING", label: "Sun Living" },
      { value: "SWIFT", label: "Swift" },
      { value: "SWISS_COMPACT", label: "Swiss Compact" },
      { value: "TABBERT", label: "Tabbert" },
      { value: "TARTARUGA", label: "Tartaruga" },
      { value: "TAURUS", label: "Taurus" },
      { value: "TEC", label: "TEC" },
      { value: "TEMPO", label: "Tempo" },
      { value: "THOMSON", label: "Thomson" },
      { value: "TIFFIN_MOTORHOMES", label: "Tiffin Motorhomes" },
      { value: "TIKRO", label: "Tikro" },
      { value: "TISCHER", label: "Tischer" },
      { value: "TOURNE_MOBIL", label: "Tourne Mobil" },
      { value: "TOYOTA", label: "Toyota" },
      { value: "TRAVEL_SUPREME", label: "Travel Supreme" },
      { value: "TRIGANO", label: "Trigano" },
      { value: "TURATELLO", label: "Turatello" },
      { value: "VAL_DE_LOIRE", label: "Val de Loire" },
      { value: "VALEUR", label: "Valeur" },
      { value: "VAN_HOOL", label: "Van Hool" },
      { value: "VANTOURER", label: "Vantourer" },
      { value: "VARIO", label: "Vario" },
      { value: "VFW", label: "VFW" },
      { value: "VL_OUTDOOR", label: "VL Outdoor" },
      { value: "VOLKNER", label: "Volkner" },
      { value: "VW", label: "VW" },
      { value: "WALDE", label: "Walde" },
      { value: "WEINSBERG", label: "Weinsberg" },
      { value: "WEIPPERT", label: "Weippert" },
      { value: "WESTFALIA", label: "Westfalia" },
      { value: "WILK", label: "Wilk" },
      { value: "WINGAMM", label: "Wingamm" },
      { value: "WINNEBAGO", label: "Winnebago" },
      { value: "WM_MEYER", label: "WM Meyer" },
      { value: "WOCHNER", label: "Wochner" },
      { value: "XGO", label: "XGO" },
      { value: "YUCON", label: "Yucon" },
    ],
  },
] as const;

export const camperBodyTypeEnum = [
  { value: "ALCOVE", label: "Alkoven" },
  { value: "TRAILER", label: "Anhänger" },
  { value: "BUS", label: "Bus" },
  { value: "INTEGRATED", label: "Integriertes Wohnmobil" },
  { value: "CAB", label: "Kabine" },
  { value: "BOX", label: "Kasten" },
  { value: "ESTATE", label: "Kombi" },
  { value: "MINIVAN", label: "Kompaktvan / Minivan" },
  { value: "PICKUP", label: "Pick-up" },
  { value: "OTHER", label: "Sonstige" },
  { value: "SUV", label: "SUV / Geländewagen" },
  { value: "SEMI_INTEGRATED", label: "Teilintegrierter" },
  { value: "MOTORHOME", label: "Wohnmobil" },
  { value: "CARAVAN", label: "Wohnwagen" },
] as const;

export const camperFuelTypeEnum = [
  { value: "PETROL", label: "Benzin" },
  { value: "ETHANOL_PETROL", label: "Bioethanol" },
  { value: "DIESEL", label: "Diesel" },
  { value: "ELECTRIC", label: "Elektro" },
  { value: "HEV_DIESEL", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "HEV_PETROL", label: "Voll-Hybrid Benzin/Elektro" },
] as const;

export const camperExtrasEnum = [
  { value: "ACCESSIBLE_FOR_DISABLED", label: "Behindertengerecht" },
  { value: "DIRECT_IMPORT", label: "Direkt-/Parallelimport" },
  { value: "ACCIDENT_VEHICLE", label: "Unfallfahrzeug" },
] as const;
