export const carMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "MERCEDES", label: "Mercedes-Benz" },
      { value: "BMW", label: "BMW" },
      { value: "AUDI", label: "Audi" },
      { value: "VOLKSWAGEN", label: "Volkswagen" },
      { value: "PORSCHE", label: "Porsche" },
      { value: "FORD", label: "Ford" },
      { value: "SKODA", label: "Skoda" },
      { value: "OPEL", label: "Opel" },
      { value: "TOYOTA", label: "Toyota" },
      { value: "VOLVO", label: "Volvo" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "9FF", label: "9ff" },
      { value: "ABARTH", label: "Abarth" },
      { value: "AC", label: "AC" },
      { value: "ACM", label: "ACM" },
      { value: "ACURA", label: "Acura" },
      { value: "AERFAL", label: "Aerfal" },
      { value: "AIWAYS", label: "Aiways" },
      { value: "AIXAM", label: "Aixam" },
      { value: "ALBA_MOBILITY", label: "Alba Mobility" },
      { value: "ALFA_ROMEO", label: "Alfa Romeo" },
      { value: "ALPINA", label: "Alpina" },
      { value: "ALPINE", label: "Alpine" },
      { value: "AMPHICAR", label: "Amphicar" },
      { value: "ANGELELLI_AUTOMOBILI", label: "Angelelli Automobili" },
      { value: "ARIEL_MOTOR", label: "Ariel Motor" },
      { value: "ARTEGA", label: "Artega" },
      { value: "ASPARK", label: "Aspark" },
      { value: "ASPID", label: "Aspid" },
      { value: "ASTON_MARTIN", label: "Aston Martin" },

      { value: "AURUS", label: "Aurus" },
      { value: "AUSTIN", label: "Austin" },
      { value: "AUSTIN_HEALEY", label: "Austin-Healey" },
      { value: "AUTOBIANCHI", label: "Autobianchi" },
      { value: "BAIC", label: "BAIC" },
      { value: "BAW", label: "BAW" },
      { value: "BEDFORD", label: "Bedford" },
      { value: "BELLIER", label: "Bellier" },
      { value: "BENTLEY", label: "Bentley" },
      { value: "BERTONE", label: "Bertone" },
      { value: "BESTUNE", label: "Bestune" },

      { value: "BOLDMEN", label: "Boldmen" },
      { value: "BOLLORE", label: "Bolloré" },
      { value: "BORGWARD", label: "Borgward" },
      { value: "BRILLIANCE", label: "Brilliance" },
      { value: "BRISTOL", label: "Bristol" },
      { value: "BRUTE", label: "Brute" },
      { value: "BUGATTI", label: "Bugatti" },
      { value: "BUICK", label: "Buick" },
      { value: "BYD", label: "BYD" },
      { value: "CADILLAC", label: "Cadillac" },
      { value: "CARAVANS_WOHNM", label: "Caravans-Wohnm" },
      { value: "CARVER", label: "Carver" },
      { value: "CASALINI", label: "Casalini" },
      { value: "CATERHAM", label: "Caterham" },
      { value: "CENNTRO", label: "Cenntro" },
      { value: "CHAMONIX", label: "Chamonix" },
      { value: "CHANGAN", label: "Changan" },
      { value: "CHANGHE", label: "Changhe" },
      { value: "CHATENET", label: "Chatenet" },
      { value: "CHERY", label: "Chery" },
      { value: "CHEVROLET", label: "Chevrolet" },
      { value: "CHRYSLER", label: "Chrysler" },
      { value: "CIRELLI", label: "Cirelli" },
      { value: "CITROEN", label: "Citroen" },
      { value: "CITYEL", label: "CityEL" },
      { value: "CORVETTE", label: "Corvette" },
      { value: "CUPRA", label: "CUPRA" },
      { value: "DACIA", label: "Dacia" },
      { value: "DAEWOO", label: "Daewoo" },
      { value: "DAF", label: "DAF" },
      { value: "DAIHATSU", label: "Daihatsu" },
      { value: "DAIMLER", label: "Daimler" },
      { value: "DALLARA", label: "Dallara" },
      { value: "DANGEL", label: "Dangel" },
      { value: "DE_LA_CHAPELLE", label: "De la Chapelle" },
      { value: "DE_TOMASO", label: "De Tomaso" },
      { value: "DELOREAN", label: "Delorean" },
      { value: "DENZA", label: "Denza" },
      { value: "DEVINCI_CARS", label: "Devinci Cars" },
      { value: "DFSK", label: "DFSK" },
      { value: "DODGE", label: "Dodge" },
      { value: "DONGFENG", label: "Dongfeng" },
      { value: "DONKERVOORT", label: "Donkervoort" },
      { value: "DR_AUTOMOBILES", label: "DR Automobiles" },
      { value: "DS_AUTOMOBILES", label: "DS Automobiles" },
      { value: "DUTTON", label: "Dutton" },
      { value: "E_GO", label: "e.GO" },
      { value: "EBRO", label: "Ebro" },
      { value: "ECONELO", label: "Econelo" },
      { value: "EDRAN", label: "Edran" },
      { value: "ELARIS", label: "Elaris" },
      { value: "EMBUGGY", label: "Embuggy" },
      { value: "EMC", label: "EMC" },
      { value: "ESTRIMA", label: "Estrima" },
      { value: "EVETTA", label: "Evetta" },
      { value: "EVO", label: "EVO" },
      { value: "FARIZON", label: "Farizon" },
      { value: "FERRARI", label: "Ferrari" },
      { value: "FIAT", label: "Fiat" },
      { value: "FISKER", label: "Fisker" },

      { value: "FORTHING", label: "Forthing" },
      { value: "FOTON", label: "Foton" },
      { value: "GAC_GONOW", label: "Gac Gonow" },
      { value: "GALLOPER", label: "Galloper" },
      { value: "GAPPY", label: "Gappy" },
      { value: "GAZ", label: "GAZ" },
      { value: "GEELY", label: "Geely" },
      { value: "GEM", label: "GEM" },
      { value: "GEMBALLA", label: "GEMBALLA" },
      { value: "GENESIS", label: "Genesis" },
      { value: "GIANA", label: "Giana" },
      { value: "GILLET", label: "Gillet" },
      { value: "GIOTTI_VICTORIA", label: "Giotti Victoria" },
      { value: "GMC", label: "GMC" },
      { value: "GOUPIL", label: "Goupil" },
      { value: "GREAT_WALL", label: "Great Wall" },
      { value: "GRECAV", label: "Grecav" },
      { value: "GTA", label: "GTA" },
      { value: "GWM", label: "GWM" },
      { value: "HAIMA", label: "Haima" },
      { value: "HAMANN", label: "Hamann" },
      { value: "HAVAL", label: "Haval" },
      { value: "HIPHI", label: "Hiphi" },
      { value: "HOLDEN", label: "Holden" },
      { value: "HONDA", label: "Honda" },
      { value: "HONGQI", label: "Hongqi" },
      { value: "HUMMER", label: "HUMMER" },
      { value: "HURTAN", label: "Hurtan" },
      { value: "HYUNDAI", label: "Hyundai" },
      { value: "ICH_X", label: "ICH-X" },
      { value: "INEOS", label: "Ineos" },
      { value: "INFINITI", label: "Infiniti" },
      { value: "INNOCENTI", label: "Innocenti" },
      { value: "INVICTA", label: "Invicta" },
      { value: "ISO_RIVOLTA", label: "Iso Rivolta" },
      { value: "ISUZU", label: "Isuzu" },
      { value: "IVECO", label: "Iveco" },
      { value: "IZH", label: "IZH" },
      { value: "JAC", label: "JAC" },
      { value: "JAECOO", label: "Jaecoo" },
      { value: "JAGUAR", label: "Jaguar" },
      { value: "JEEP", label: "Jeep" },
      { value: "JENSEN", label: "Jensen" },
      { value: "KARMA", label: "Karma" },
      { value: "KGM", label: "KGM" },
      { value: "KIA", label: "Kia" },
      { value: "KOENIGSEGG", label: "Koenigsegg" },
      { value: "KTM", label: "KTM" },
      { value: "LADA", label: "Lada" },
      { value: "LAMBORGHINI", label: "Lamborghini" },
      { value: "LANCIA", label: "Lancia" },
      { value: "LAND_ROVER", label: "Land Rover" },
      { value: "LDV", label: "LDV" },
      { value: "LEAPMOTOR", label: "Leapmotor" },
      { value: "LEE_GROUP", label: "Lee Group" },
      { value: "LEVC", label: "LEVC" },
      { value: "LEXUS", label: "Lexus" },
      { value: "LI", label: "Li" },
      { value: "LIFAN", label: "Lifan" },
      { value: "LIGIER", label: "Ligier" },
      { value: "LINCOLN", label: "Lincoln" },
      { value: "LINZDA", label: "Linzda" },
      { value: "LIVAN", label: "Livan" },
      { value: "LORINSER", label: "Lorinser" },
      { value: "LOTUS", label: "Lotus" },
      { value: "LUCID", label: "Lucid" },
      { value: "LYNK_CO", label: "Lynk & Co" },
      { value: "M_ERO", label: "M-Ero" },
      { value: "MAHINDRA", label: "Mahindra" },
      { value: "MAN", label: "MAN" },
      { value: "MANSORY", label: "Mansory" },
      { value: "MARTIN", label: "Martin" },
      { value: "MARTIN_MOTORS", label: "Martin Motors" },
      { value: "MASERATI", label: "Maserati" },
      { value: "MATRA", label: "Matra" },
      { value: "MAXUS", label: "Maxus" },
      { value: "MAYBACH", label: "Maybach" },
      { value: "MAZDA", label: "Mazda" },
      { value: "MCLAREN", label: "McLaren" },
      { value: "MEGA", label: "Mega" },
      { value: "MELEX", label: "Melex" },

      { value: "MERCURY", label: "Mercury" },
      { value: "MG", label: "MG" },
      { value: "MICRO", label: "Micro" },
      { value: "MICROCAR", label: "Microcar" },
      { value: "MILITEM", label: "Militem" },
      { value: "MINARI", label: "Minari" },
      { value: "MINAUTO", label: "Minauto" },
      { value: "MINI", label: "MINI" },
      { value: "MITSUBISHI", label: "Mitsubishi" },
      { value: "MITSUOKA", label: "Mitsuoka" },
      { value: "MOBILIZE", label: "Mobilize" },
      { value: "MORGAN", label: "Morgan" },
      { value: "MOSKVICH", label: "Moskvich" },
      { value: "MP_LAFER", label: "MP Lafer" },
      { value: "MPM_MOTORS", label: "MPM Motors" },
      { value: "NIO", label: "NIO" },
      { value: "NISSAN", label: "Nissan" },
      { value: "NSU", label: "NSU" },
      { value: "OLDSMOBILE", label: "Oldsmobile" },
      { value: "OLDTIMER", label: "Oldtimer" },
      { value: "OMODA", label: "Omoda" },

      { value: "ORA", label: "Ora" },
      { value: "PAGANI", label: "Pagani" },
      { value: "PANTHER_WESTWINDS", label: "Panther Westwinds" },
      { value: "PEUGEOT", label: "Peugeot" },
      { value: "PGO", label: "PGO" },
      { value: "PIAGGIO", label: "Piaggio" },
      { value: "PLYMOUTH", label: "Plymouth" },
      { value: "POLESTAR", label: "Polestar" },
      { value: "PONTIAC", label: "Pontiac" },
      { value: "PROTON", label: "Proton" },
      { value: "PUCH", label: "Puch" },
      { value: "RAM", label: "RAM" },
      { value: "REGIS", label: "Regis" },
      { value: "RELIANT", label: "Reliant" },

      { value: "RIVIAN", label: "Rivian" },
      { value: "ROLLS_ROYCE", label: "Rolls-Royce" },
      { value: "ROVER", label: "Rover" },
      { value: "RUF", label: "Ruf" },
      { value: "SAAB", label: "Saab" },
      { value: "SANTANA", label: "Santana" },
      { value: "SEAT", label: "SEAT" },
      { value: "SEGWAY", label: "Segway" },
      { value: "SELVO", label: "Selvo" },
      { value: "SERES", label: "Seres" },
      { value: "SEVIC", label: "Sevic" },
      { value: "SGS", label: "SGS" },
      { value: "SHELBY", label: "Shelby" },
      { value: "SHUANGHUAN", label: "Shuanghuan" },
      { value: "SILENCE", label: "Silence" },
      { value: "SIMPLICI", label: "Simplici" },
      { value: "SINGER", label: "Singer" },
      { value: "SKYWELL", label: "Skywell" },
      { value: "SMART", label: "smart" },
      { value: "SPEEDART", label: "SpeedArt" },
      { value: "SPORTEQUIPE", label: "Sportequipe" },
      { value: "SPYKER", label: "Spyker" },
      { value: "SSANGYONG", label: "SsangYong" },
      { value: "STORMBORN", label: "Stormborn" },
      { value: "STREETSCOOTER", label: "StreetScooter" },
      { value: "STUDEBAKER", label: "Studebaker" },
      { value: "SUBARU", label: "Subaru" },
      { value: "SUZUKI", label: "Suzuki" },
      { value: "SWM", label: "SWM" },
      { value: "TALBOT", label: "Talbot" },
      { value: "TASSO", label: "Tasso" },
      { value: "TATA", label: "Tata" },
      { value: "TAZZARI_EV", label: "Tazzari EV" },
      { value: "TECHART", label: "TECHART" },
      { value: "TESLA", label: "Tesla" },
      { value: "TIGER", label: "Tiger" },
      { value: "TOGG", label: "Togg" },
      { value: "TOWN_LIFE", label: "Town Life" },
      { value: "TRABANT", label: "Trabant" },
      { value: "TRAILER_ANHANGER", label: "Trailer-Anhänger" },
      { value: "TRIUMPH", label: "Triumph" },
      { value: "TRUCKS_LKW", label: "Trucks-Lkw" },
      { value: "TVR", label: "TVR" },
      { value: "UAZ", label: "UAZ" },
      { value: "VANDEN_PLAS", label: "Vanden Plas" },
      { value: "VANDERHALL", label: "Vanderhall" },
      { value: "VAZ", label: "VAZ" },
      { value: "VEM", label: "VEM" },
      { value: "VINFAST", label: "VinFast" },

      { value: "VOYAH", label: "Voyah" },
      { value: "WARTBURG", label: "Wartburg" },
      { value: "WELTMEISTER", label: "Weltmeister" },
      { value: "WENCKSTERN", label: "Wenckstern" },
      { value: "WESTFIELD", label: "Westfield" },
      { value: "WEY", label: "Wey" },
      { value: "WIESMANN", label: "Wiesmann" },
      { value: "XBUS", label: "XBus" },
      { value: "XEV", label: "XEV" },
      { value: "XIAOMI", label: "Xiaomi" },
      { value: "XPENG", label: "Xpeng" },
      { value: "ZASTAVA", label: "Zastava" },
      { value: "ZAZ", label: "ZAZ" },
      { value: "ZEEKR", label: "Zeekr" },
      { value: "ZHIDOU", label: "Zhidou" },
      { value: "ZOTYE", label: "Zotye" },
      { value: "OTHERS", label: "Others" },
    ],
  },
] as const;

export const carModels: Record<string, { value: string; label: string }[]> = {
  AUDI: [
    { value: "A1", label: "A1" },
    { value: "A3", label: "A3" },
    { value: "A4", label: "A4" },
    { value: "A6", label: "A6" },
    { value: "A8", label: "A8" },
    { value: "Q3", label: "Q3" },
    { value: "Q5", label: "Q5" },
    { value: "Q7", label: "Q7" },
    { value: "Q8", label: "Q8" },
    { value: "TT", label: "TT" },
    { value: "R8", label: "R8" },
    { value: "E_TRON", label: "e-tron" },
  ],
  BMW: [
    { value: "1_SERIES", label: "1 Series" },
    { value: "2_SERIES", label: "2 Series" },
    { value: "3_SERIES", label: "3 Series" },
    { value: "4_SERIES", label: "4 Series" },
    { value: "5_SERIES", label: "5 Series" },
    { value: "7_SERIES", label: "7 Series" },
    { value: "X1", label: "X1" },
    { value: "X3", label: "X3" },
    { value: "X5", label: "X5" },
    { value: "X7", label: "X7" },
    { value: "I4", label: "i4" },
    { value: "I8", label: "i8" },
    { value: "IX", label: "iX" },
  ],
  MERCEDES: [
    { value: "A_CLASS", label: "A-Class" },
    { value: "C_CLASS", label: "C-Class" },
    { value: "E_CLASS", label: "E-Class" },
    { value: "S_CLASS", label: "S-Class" },
    { value: "GLA", label: "GLA" },
    { value: "GLB", label: "GLB" },
    { value: "GLC", label: "GLC" },
    { value: "GLE", label: "GLE" },
    { value: "GLS", label: "GLS" },
    { value: "EQC", label: "EQC" },
    { value: "EQS", label: "EQS" },
  ],
  VOLKSWAGEN: [
    { value: "GOLF", label: "Golf" },
    { value: "POLO", label: "Polo" },
    { value: "PASSAT", label: "Passat" },
    { value: "TIGUAN", label: "Tiguan" },
    { value: "TOUAREG", label: "Touareg" },
    { value: "T_ROC", label: "T-Roc" },
    { value: "ARTEON", label: "Arteon" },
    { value: "ID3", label: "ID.3" },
    { value: "ID4", label: "ID.4" },
  ],
  PORSCHE: [
    { value: "911", label: "911" },
    { value: "718", label: "718" },
    { value: "CAYENNE", label: "Cayenne" },
    { value: "MACAN", label: "Macan" },
    { value: "PANAMERA", label: "Panamera" },
    { value: "TAYCAN", label: "Taycan" },
  ],
  FORD: [
    { value: "FIESTA", label: "Fiesta" },
    { value: "FOCUS", label: "Focus" },
    { value: "MUSTANG", label: "Mustang" },
    { value: "EXPLORER", label: "Explorer" },
    { value: "F150", label: "F-150" },
    { value: "RANGER", label: "Ranger" },
    { value: "EDGE", label: "Edge" },
  ],
  TOYOTA: [
    { value: "COROLLA", label: "Corolla" },
    { value: "CAMRY", label: "Camry" },
    { value: "RAV4", label: "RAV4" },
    { value: "HIGHLANDER", label: "Highlander" },
    { value: "PRIUS", label: "Prius" },
    { value: "LANDCRUISER", label: "Land Cruiser" },
    { value: "YARIS", label: "Yaris" },
  ],
  HONDA: [
    { value: "CIVIC", label: "Civic" },
    { value: "ACCORD", label: "Accord" },
    { value: "CRV", label: "CR-V" },
    { value: "HRV", label: "HR-V" },
    { value: "PILOT", label: "Pilot" },
    { value: "FIT", label: "Fit" },
  ],
  NISSAN: [
    { value: "ALTIMA", label: "Altima" },
    { value: "MAXIMA", label: "Maxima" },
    { value: "SENTRA", label: "Sentra" },
    { value: "ROGUE", label: "Rogue" },
    { value: "MURANO", label: "Murano" },
    { value: "PATHFINDER", label: "Pathfinder" },
    { value: "LEAF", label: "Leaf" },
  ],
  HYUNDAI: [
    { value: "ELANTRA", label: "Elantra" },
    { value: "SONATA", label: "Sonata" },
    { value: "TUCSON", label: "Tucson" },
    { value: "SANTA_FE", label: "Santa Fe" },
    { value: "KONA", label: "Kona" },
    { value: "IONIQ", label: "Ioniq" },
  ],
} as const;

export const popularCarMakes = [
  {
    name: "Mercedes-Benz",
    logo: "/brand-logos/mercedes-benz.png",
  },
  {
    name: "BMW",
    logo: "/brand-logos/bmw.png",
  },
  {
    name: "Audi",
    logo: "/brand-logos/audi.png",
  },
  {
    name: "VW",
    logo: "/brand-logos/vw.png",
  },
  {
    name: "Porsche",
    logo: "/brand-logos/porsche.png",
  },
  {
    name: "Toyota",
    logo: "/brand-logos/toyota.png",
  },
  {
    name: "Ford",
    logo: "/brand-logos/ford.png",
  },
  {
    name: "Skoda",
    logo: "/brand-logos/skoda.png",
  },
  {
    name: "Renault",
    logo: "/brand-logos/renault.png",
  },
  {
    name: "Volvo",
    logo: "/brand-logos/volvo.png",
  },
  {
    name: "Fiat",
    logo: "/brand-logos/fiat.png",
  },
  {
    name: "Seat",
    logo: "/brand-logos/seat.png",
  },
] as const;

export const carBodyTypeEnum = [
  { value: "BUS", label: "Bus" },
  { value: "CABRIOLET", label: "Cabriolet" },
  { value: "COUPE", label: "Coupé" },
  { value: "SMALL_CAR", label: "Kleinwagen" },
  { value: "ESTATE", label: "Kombi" },
  { value: "MINIVAN", label: "Kompaktvan / Minivan" },
  { value: "SALOON", label: "Limousine" },
  { value: "PICKUP", label: "Pick-up" },
  { value: "SUV", label: "SUV / Geländewagen" },
] as const;

export const carFuelTypeEnum = [
  { value: "PETROL", label: "Benzin" },
  { value: "ETHANOL_PETROL", label: "Bioethanol" },
  { value: "DIESEL", label: "Diesel" },
  { value: "ELECTRIC", label: "Elektro" },
  { value: "CNG_PETROL", label: "Erdgas (CNG) / Benzin" },
  { value: "LPG_PETROL", label: "Flüssiggas (LPG) / Benzin" },
  { value: "MHEV_DIESEL", label: "Mild-Hybrid Diesel/Elektro" },
  { value: "MHEV_PETROL", label: "Mild-Hybrid Benzin/Elektro" },
  { value: "PHEV_DIESEL", label: "Plug-in hybrid Diesel/Elektro" },
  { value: "PHEV_PETROL", label: "Plug-in hybrid Benzin/Elektro" },
  { value: "HEV_DIESEL", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "HEV_PETROL", label: "Voll-Hybrid Benzin/Elektro" },
  { value: "HYDROGEN", label: "Wasserstoff" },
] as const;

export const carExtrasEnum = [
  { value: "8_TYRES", label: "8-fach bereift" },
  { value: "ACCESSIBLE_FOR_DISABLED", label: "Behindertengerecht" },
  { value: "DIRECT_IMPORT", label: "Direkt-/Parallelimport" },
  { value: "RACE_CAR", label: "Rennwagen" },
  { value: "TUNING", label: "Tuning" },
  { value: "ACCIDENT_VEHICLE", label: "Unfallfahrzeug" },
] as const;
