export const utilityMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "FIAT", label: "Fiat" },
      { value: "FORD", label: "Ford" },
      { value: "IVECO", label: "Iveco" },
      { value: "MAN", label: "MAN" },
      { value: "MERCEDES_BENZ", label: "Mercedes-Benz" },
      { value: "NISSAN", label: "Nissan" },
      { value: "PEUGEOT", label: "Peugeot" },
      { value: "RENAULT", label: "Renault" },
      { value: "TOYOTA", label: "Toyota" },
      { value: "VW", label: "VW" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "AC", label: "AC" },
      { value: "ADDAX_MOTORS", label: "Addax Motors" },
      { value: "AEBI", label: "Aebi" },
      { value: "AGADOS", label: "Agados" },
      { value: "ALKE", label: "Alke" },
      { value: "ALVIS", label: "Alvis" },
      { value: "AUTOBIANCHI", label: "Autobianchi" },
      { value: "BAW", label: "BAW" },
      { value: "BEDFORD", label: "Bedford" },
      { value: "BLYSS", label: "Blyss" },
      { value: "BNM", label: "BNM" },
      { value: "BOCKMANN", label: "Böckmann" },
      { value: "BOSCHUNG", label: "Boschung" },
      { value: "BREMACH", label: "Bremach" },
      { value: "BTALMOBIL", label: "Btalmobil" },
      { value: "BUCHER", label: "Bucher" },
      { value: "BURSTNER", label: "Bürstner" },
      { value: "BYD", label: "BYD" },
      { value: "CENNTRO", label: "Cenntro" },
      { value: "CHEVROLET", label: "Chevrolet" },
      { value: "CITROEN", label: "Citroen" },
      { value: "DACIA", label: "Dacia" },
      { value: "DAIHATSU", label: "Daihatsu" },
      { value: "DALTEC", label: "Daltec" },
      { value: "DEUTZ_FAHR", label: "Deutz-Fahr" },
      { value: "DFM", label: "DFM" },
      { value: "DFSK", label: "DFSK" },
      { value: "DISALCAR", label: "Disalcar" },
      { value: "DKW", label: "DKW" },
      { value: "DODGE", label: "Dodge" },
      { value: "ELARIS", label: "Elaris" },
      { value: "EQUI_TREK", label: "Equi-Trek" },
      { value: "EVITALIA", label: "Evitalia" },
      { value: "FBW", label: "FBW" },
      { value: "FITZEL", label: "Fitzel" },
      { value: "FORTHING", label: "Forthing" },
      { value: "FUSO", label: "Fuso" },
      { value: "GAC_GONOW", label: "Gac Gonow" },
      { value: "GAZ", label: "GAZ" },
      { value: "GIOTTI_VICTORIA", label: "Giotti Victoria" },
      { value: "GLADIATOR", label: "Gladiator" },
      { value: "GMC", label: "GMC" },
      { value: "GOUPIL", label: "Goupil" },
      { value: "HANOMAG", label: "Hanomag" },
      { value: "HOBBY", label: "Hobby" },
      { value: "HONDA", label: "Honda" },
      { value: "HRB", label: "HRB" },
      { value: "HUDSON", label: "Hudson" },
      { value: "HUMBAUR", label: "Humbaur" },
      { value: "HYUNDAI", label: "Hyundai" },
      { value: "IFOR", label: "Ifor" },
      { value: "INEOS", label: "Ineos" },
      { value: "INTERNATIONAL", label: "International" },
      { value: "ISUZU", label: "Isuzu" },
      { value: "JAC", label: "JAC" },
      { value: "JEEP", label: "Jeep" },
      { value: "JIAYUAN", label: "Jiayuan" },
      { value: "JOHN_DEERE", label: "John Deere" },
      { value: "KAESSBOHRER", label: "Kaessbohrer" },
      { value: "KARMANN", label: "Karmann" },
      { value: "KGM_SSANGYONG", label: "KGM-SsangYong" },
      { value: "KIA", label: "Kia" },
      { value: "KLINGLER", label: "Klingler" },
      { value: "LADOG", label: "Ladog" },
      { value: "LANCIA", label: "Lancia" },
      { value: "LAND_ROVER", label: "Land Rover" },
      { value: "LEVC", label: "LEVC" },
      { value: "LINCOLN", label: "Lincoln" },
      { value: "LINDNER", label: "Lindner" },
      { value: "MAXUS", label: "Maxus" },
      { value: "MAZDA", label: "Mazda" },
      { value: "MEGA", label: "Mega" },
      { value: "MEILI", label: "Meili" },
      { value: "MINI", label: "Mini" },
      { value: "MITSUBISHI", label: "Mitsubishi" },
      { value: "MITSUBISHI_FUSO", label: "Mitsubishi Fuso" },
      { value: "MLT", label: "MLT" },
      { value: "MORRIS", label: "Morris" },
      { value: "MOWAG", label: "Mowag" },
      { value: "OM", label: "OM" },
      { value: "OPEL", label: "Opel" },
      { value: "PIAGGIO", label: "Piaggio" },
      { value: "PINZGAUER", label: "Pinzgauer" },
      { value: "PONY", label: "Pony" },
      { value: "PUCH", label: "Puch" },
      { value: "RAVO", label: "Ravo" },
      { value: "ROLBA", label: "Rolba" },
      { value: "RUSKA", label: "Ruska" },
      { value: "SANTANA", label: "Santana" },
      { value: "SARIS", label: "Saris" },
      { value: "SAURER", label: "Saurer" },
      { value: "SCHWARZMULLER", label: "Schwarzmüller" },
      { value: "SEAT", label: "SEAT" },
      { value: "SETRA", label: "Setra" },
      { value: "SKODA", label: "Skoda" },
      { value: "SOKON", label: "Sokon" },
      { value: "SOLIS", label: "Solis" },
      { value: "STEYR", label: "Steyr" },
      { value: "STREETSCOOTER", label: "Streetscooter" },
      { value: "STUSSI", label: "Stüssi" },
      { value: "SUZUKI", label: "Suzuki" },
      { value: "TATA", label: "Tata" },
      { value: "TATRA", label: "Tatra" },
      { value: "TEMPO", label: "Tempo" },
      { value: "TGB", label: "TGB" },
      { value: "TROPOS", label: "Tropos" },
      { value: "TYN_E", label: "TYN-e" },
      { value: "UAZ", label: "UAZ" },
      { value: "UNIMOG", label: "Unimog" },
      { value: "VAN_HOOL", label: "Van Hool" },
      { value: "VEM", label: "VEM" },
      { value: "WALDE", label: "Walde" },
      { value: "WEIJER_W1", label: "Weijer W1" },
      { value: "WILLYS", label: "Willys" },
      { value: "WM_MEYER", label: "WM Meyer" },
      { value: "ZBINDEN", label: "Zbinden" },
    ],
  },
] as const;

export const utilityModels: Record<string, { value: string; label: string }[]> =
  {
    BYD: [
      { value: "ETM6", label: "ETM6" },
      { value: "ETP3", label: "ETP3" },
      { value: "T3", label: "T3" },
    ],
    BOSCHUNG: [{ value: "PONY_P4_T", label: "Pony P4-T" }],
    CENNTRO: [
      { value: "LOGISTAR_100", label: "Logistar 100" },
      { value: "LOGISTAR_200", label: "Logistar 200" },
      { value: "LOGISTAR_260", label: "Logistar 260" },
      { value: "METRO", label: "Metro" },
      { value: "TEEMAK", label: "Teemak" },
    ],
    CHEVROLET: [
      { value: "ASTRO", label: "Astro" },
      { value: "BLAZER", label: "Blazer" },
      { value: "C_K_PICKUP", label: "C/K Pickup" },
      { value: "EXPRESS", label: "Express" },
      { value: "G_VAN", label: "G-Van" },
    ],
    DACIA: [
      { value: "DOKKER", label: "Dokker" },
      { value: "LOGAN", label: "Logan" },
    ],
    DAIHATSU: [
      { value: "CAB_VAN_PICK", label: "Cab Van/Pick" },
      { value: "HIJET", label: "Hijet" },
      { value: "ROCKY", label: "Rocky" },
    ],
    DFSK: [
      { value: "C_SERIE", label: "C-Serie" },
      { value: "K_SERIE", label: "K-Serie" },
      { value: "V_SERIE", label: "V-Serie" },
    ],
    ELARIS: [{ value: "CARO", label: "Caro" }],
    FIAT: [
      { value: "DOBLO", label: "Doblo" },
      { value: "DUCATO", label: "Ducato" },
      { value: "FIORINO", label: "Fiorino" },
      { value: "FULLBACK", label: "Fullback" },
      { value: "PANDA_VAN", label: "Panda Van" },
      { value: "SCUDO", label: "Scudo" },
      { value: "STRADA", label: "Strada" },
      { value: "TALENTO", label: "Talento" },
    ],
    FORTHING: [{ value: "6", label: "6" }],
    GIOTTI_VICTORIA: [{ value: "GLADIATOR", label: "Gladiator" }],
    GLADIATOR: [{ value: "KIPPER", label: "Kipper" }],
    GMC: [
      { value: "CANYON", label: "Canyon" },
      { value: "SAVANA", label: "Savana" },
      { value: "SIERRA", label: "Sierra" },
    ],
    HONDA: [
      { value: "ACTY", label: "Acty" },
      { value: "RIDGELINE", label: "Ridgeline" },
    ],
    HYUNDAI: [
      { value: "H_1", label: "H-1" },
      { value: "H_100", label: "H 100" },
      { value: "H_350", label: "H 350" },
      { value: "SATELLITE", label: "Satellite" },
    ],
    INEOS: [{ value: "GRENADIER", label: "Grenadier" }],
    ISUZU: [
      { value: "BTFS", label: "BTFS" },
      { value: "D_MAX", label: "D-MAX" },
      { value: "KB_CAMPO", label: "KB/CAMPO" },
      { value: "M21", label: "M21" },
      { value: "M27", label: "M27" },
      { value: "MIDI", label: "Midi" },
      { value: "N_EVO", label: "N-EVO" },
      { value: "NKR", label: "NKR" },
      { value: "NKR_77", label: "NKR 77" },
      { value: "NKR_85", label: "NKR 85" },
      { value: "NLR_85", label: "NLR 85" },
      { value: "NLR_85A", label: "NLR 85A" },
      { value: "NLR_87", label: "NLR 87" },
      { value: "NMR_85", label: "NMR 85" },
      { value: "NNR_85", label: "NNR 85" },
      { value: "NNR_87", label: "NNR 87" },
      { value: "NPR_75", label: "NPR 75" },
      { value: "NPR_77", label: "NPR 77" },
      { value: "NPR_85", label: "NPR 85" },
      { value: "OBD_D_N_L35", label: "OBD-D N-L35" },
      { value: "OBD_D_N_M55", label: "OBD-D N-M55" },
      { value: "OBD_D_N_N35", label: "OBD-D N-N35" },
      { value: "OBD_D_N_P65", label: "OBD-D N-P65" },
      { value: "OBD_D_N_P75", label: "OBD-D N-P75" },
      { value: "OBD_E", label: "OBD-E" },
      { value: "TFS_85", label: "TFS 85" },
      { value: "WFR", label: "WFR" },
      { value: "WFS", label: "WFS" },
    ],
    IVECO: [
      { value: "50_10_35", label: "50-10/35" },
      { value: "DAILY", label: "Daily" },
      { value: "DAILY_CITY", label: "Daily City" },
      { value: "E_DAILY", label: "E Daily" },
      { value: "ECODAILY", label: "Ecodaily" },
      { value: "MASSIF", label: "Massif" },
      { value: "TURBO_DAILY", label: "Turbo-Daily" },
    ],
    JAC: [
      { value: "M3EV", label: "M3EV" },
      { value: "T8_PRO", label: "T8 Pro" },
      { value: "T9EV_4X4", label: "T9EV 4x4" },
    ],
    JEEP: [{ value: "GLADIATOR", label: "Gladiator" }],
    KAESSBOHRER: [{ value: "SETRA_S9A", label: "Setra S9A" }],
    KGM_SSANGYONG: [{ value: "MUSSO", label: "Musso" }],
    KIA: [
      { value: "K2500", label: "K2500" },
      { value: "K2900", label: "K2900" },
      { value: "PREGIO", label: "Pregio" },
      { value: "PREGIO_II", label: "Pregio II" },
      { value: "PV5", label: "PV5" },
    ],
    LANCIA: [{ value: "Z_TURBO", label: "Z Turbo" }],
    LAND_ROVER: [
      { value: "88_110", label: "88 - 110" },
      { value: "DEFENDER", label: "Defender" },
    ],
    LEVC: [
      { value: "TX", label: "TX" },
      { value: "VN", label: "VN" },
    ],
    MAN: [{ value: "TGE", label: "TGE" }],
    MAXUS: [
      { value: "DELIVER_7", label: "Deliver 7" },
      { value: "DELIVER_9", label: "Deliver 9" },
      { value: "EDELIVER_3", label: "eDeliver 3" },
      { value: "EDELIVER_5", label: "eDeliver 5" },
      { value: "EDELIVER_7", label: "eDeliver 7" },
      { value: "EDELIVER_9", label: "eDeliver 9" },
      { value: "ETERRON_9", label: "eTerron 9" },
      { value: "EUNIQ_6", label: "eUniq 6" },
      { value: "EV80", label: "EV80" },
      { value: "T60", label: "T60" },
      { value: "T90_EV", label: "T90 EV" },
    ],
    MAZDA: [
      { value: "B_2500", label: "B 2500" },
      { value: "BT_50", label: "BT-50" },
      { value: "E_1600", label: "E 1600" },
      { value: "E_2000", label: "E 2000" },
      { value: "E_2200", label: "E 2200" },
    ],
    MEGA: [{ value: "MEGA", label: "Mega" }],
    MERCEDES_BENZ: [
      { value: "100_SERIES", label: "100 Series" },
      { value: "200_SERIES", label: "200-Series" },
      { value: "215", label: "215" },
      { value: "218", label: "218" },
      { value: "224", label: "224" },
      { value: "300_SERIES", label: "300-Series" },
      { value: "313", label: "313" },
      { value: "314_CDI", label: "314 CDI" },
      { value: "400_SERIES", label: "400-Series" },
      { value: "411", label: "411" },
      { value: "414", label: "414" },
      { value: "500_SERIES", label: "500-Series" },
      { value: "509", label: "509" },
      { value: "511", label: "511" },
      { value: "515", label: "515" },
      { value: "524", label: "524" },
      { value: "600_SERIES", label: "600-Series" },
      { value: "616", label: "616" },
      { value: "CITAN", label: "Citan" },
      { value: "E_22_BUS", label: "E 2.2 Bus" },
      { value: "ECITAN", label: "eCitan" },
      { value: "EQV_300", label: "EQV 300" },
      { value: "MARCO_POLO", label: "Marco Polo" },
      { value: "SPRINTER", label: "Sprinter" },
      { value: "T_CLASS", label: "T-Class" },
      { value: "VIANO", label: "Viano" },
      { value: "VITO", label: "Vito" },
      { value: "X_220", label: "X 220" },
      { value: "X_250", label: "X 250" },
      { value: "X_350", label: "X 350" },
    ],
    MINI: [{ value: "CLUBVAN", label: "Clubvan" }],
    MITSUBISHI_FUSO: [{ value: "CANTER", label: "Canter" }],
    MITSUBISHI: [
      { value: "CANTER", label: "Canter" },
      { value: "L_200", label: "L 200" },
      { value: "L_300", label: "L 300" },
      { value: "L_400", label: "L 400" },
    ],
    NISSAN: [
      { value: "ATLEON", label: "Atleon" },
      { value: "CABSTAR", label: "Cabstar" },
      { value: "CABSTAR_E", label: "Cabstar E" },
      { value: "E_NV200", label: "e-NV200" },
      { value: "INTERSTAR", label: "Interstar" },
      { value: "KING_DOUBLE", label: "King-/Double" },
      { value: "KUBISTAR", label: "Kubistar" },
      { value: "NAVARA", label: "Navara" },
      { value: "NP300_PICKUP", label: "NP300 Pickup" },
      { value: "NV200", label: "NV200" },
      { value: "NV250", label: "NV250" },
      { value: "NV300", label: "NV300" },
      { value: "NV400", label: "NV400" },
      { value: "PRIMASTAR", label: "Primastar" },
      { value: "SUNNY", label: "Sunny" },
      { value: "TOWNSTAR", label: "Townstar" },
      { value: "TRADE", label: "Trade" },
      { value: "URVAN", label: "Urvan" },
      { value: "VANETTE", label: "Vanette" },
    ],
    OPEL: [
      { value: "BLITZ", label: "Blitz" },
      { value: "CAMPO", label: "Campo" },
      { value: "COMBO", label: "Combo" },
      { value: "INSIGNIA", label: "Insignia" },
      { value: "MOVANO", label: "Movano" },
      { value: "REKORD", label: "Rekord" },
      { value: "VIVARO", label: "Vivaro" },
      { value: "ZAFIRA", label: "Zafira" },
    ],
    PEUGEOT: [
      { value: "BIPPER", label: "Bipper" },
      { value: "BOXER", label: "Boxer" },
      { value: "E_EXPERT", label: "E-Expert" },
      { value: "E_PARTNER", label: "E-Partner" },
      { value: "EXPERT", label: "Expert" },
      { value: "J_9", label: "J 9" },
      { value: "J5", label: "J5" },
      { value: "PARTNER", label: "Partner" },
      { value: "TRAVELLER", label: "Traveller" },
    ],
    PIAGGIO: [
      { value: "APE", label: "Ape" },
      { value: "MAXXI", label: "Maxxi" },
      { value: "PORTER", label: "Porter" },
      { value: "QUARGO", label: "Quargo" },
    ],
    PUCH: [
      { value: "290", label: "290" },
      { value: "HAFLINGER", label: "Haflinger" },
    ],
    RENAULT: [
      { value: "4_F", label: "4 F" },
      { value: "ALASKAN", label: "Alaskan" },
      { value: "B_120", label: "B 120" },
      { value: "B_90", label: "B 90" },
      { value: "EXPRESS", label: "Express" },
      { value: "KANGOO", label: "Kangoo" },
      { value: "KANGOO_COMP", label: "Kangoo Comp." },
      { value: "KANGOO_EXPR", label: "Kangoo Expr." },
      { value: "KANGOO_MAXI", label: "Kangoo Maxi" },
      { value: "MASCOTT", label: "Mascott" },
      { value: "MASTER", label: "Master" },
      { value: "MAXITY", label: "Maxity" },
      { value: "MESSENGER", label: "Messenger" },
      { value: "TRAFIC", label: "Trafic" },
      { value: "TWIZY", label: "Twizy" },
    ],
    SEAT: [
      { value: "INCA", label: "Inca" },
      { value: "TERRA", label: "Terra" },
    ],
    SKODA: [
      { value: "135_136", label: "135 / 136" },
      { value: "PRAKTIK", label: "Praktik" },
    ],
    SOKON: [{ value: "MINI_TRUCK", label: "Mini Truck" }],
    STREETSCOOTER: [
      { value: "WORK_BOX", label: "Work Box" },
      { value: "WORK_PICK_UP", label: "Work Pick-Up" },
      { value: "WORK_PURE", label: "Work Pure" },
    ],
    SUZUKI: [
      { value: "CARRY", label: "Carry" },
      { value: "NKR_85", label: "NKR 85" },
      { value: "SUPER_CARRY", label: "Super Carry" },
    ],
    TATA: [
      { value: "PICK_UP", label: "Pick Up" },
      { value: "TELCOLINE", label: "Telcoline" },
    ],
    TOYOTA: [
      { value: "DYNA", label: "Dyna" },
      { value: "HI_ACE", label: "Hi-Ace" },
      { value: "HI_LUX", label: "Hi-Lux" },
      { value: "LAND_CRUISER", label: "Land Cruiser" },
      { value: "LANDCRUISER", label: "Landcruiser" },
      { value: "LITE_ACE", label: "Lite-Ace" },
      { value: "PROACE", label: "Proace" },
      { value: "PROACE_CITY", label: "Proace City" },
      { value: "PROACE_MAX", label: "Proace Max" },
      { value: "PROACE_VERSO", label: "Proace Verso" },
      { value: "TACOMA", label: "Tacoma" },
    ],
    TYN_E: [
      { value: "LTX", label: "LTX" },
      { value: "TX1_E", label: "TX1-e" },
      { value: "TX7_E", label: "TX7-e" },
    ],
    VEM: [
      { value: "CARGO", label: "Cargo" },
      { value: "COVER", label: "Cover" },
      { value: "DOUBLE", label: "Double" },
      { value: "FREEZE", label: "Freeze" },
      { value: "MULTI", label: "Multi" },
      { value: "OPEN", label: "Open" },
      { value: "OPEN_RIBALT", label: "Open Ribalt." },
      { value: "OPEN_RSU", label: "Open RSU" },
      { value: "PEOPLE", label: "People" },
    ],
    VW: [
      { value: "AMAROK", label: "Amarok" },
      { value: "ANFIBIO", label: "Anfibio" },
      { value: "BUS", label: "Bus" },
      { value: "CADDY", label: "Caddy" },
      { value: "CRAFTER", label: "Crafter" },
      { value: "GRAND_CALIFORNIA", label: "Grand California" },
      { value: "IDBUZZ", label: "ID.Buzz" },
      { value: "LT", label: "LT" },
      { value: "T1", label: "T1" },
      { value: "T2", label: "T2" },
      { value: "T3", label: "T3" },
      { value: "T4", label: "T4" },
      { value: "T5", label: "T5" },
      { value: "T6", label: "T6" },
      { value: "T61", label: "T6.1" },
      { value: "T7_MULTIVAN", label: "T7 Multivan" },
      { value: "TARO", label: "Taro" },
      { value: "TRANSPORTER", label: "Transporter" },
    ],
  };

export const utilityBodyTypeEnum = [
  { value: "BRIDGE", label: "Brücke" },
  { value: "BRIDGE_DOUBLE_CAB", label: "Brücke mit Doppelkabine" },
  { value: "BUS", label: "Bus" },
  { value: "CHASSIS_CAB", label: "Chassis Kabine" },
  { value: "BOX", label: "Kasten" },
  { value: "BOX_GLAZED", label: "Kasten verglast" },
  { value: "BOX_DOUBLE_CAB", label: "Kastenwagen Doppelkabine" },
  { value: "TIPPER", label: "Kipper" },
  { value: "ESTATE", label: "Kombi" },
  { value: "MINIVAN", label: "Kompaktvan / Minivan" },
  { value: "PICKUP", label: "Pick-up" },
  { value: "PLATFORM", label: "Platform" },
  { value: "SEMI_TRAILER", label: "Sattel-Auflieger" },
  { value: "SUV", label: "SUV / Geländewagen" },
] as const;

export const utilityFuelTypeEnum = [
  { value: "PETROL", label: "Benzin" },
  { value: "DIESEL", label: "Diesel" },
  { value: "ELECTRIC", label: "Elektro" },
  { value: "CNG_PETROL", label: "Erdgas (CNG) / Benzin" },
  { value: "LPG_PETROL", label: "Flüssiggas (LPG) / Benzin" },
  { value: "MHEV_DIESEL", label: "Mild-Hybrid Diesel/Elektro" },
  { value: "MHEV_PETROL", label: "Mild-Hybrid Benzin/Elektro" },
  { value: "PHEV_DIESEL", label: "Plug-in hybrid Diesel/Elektro" },
  { value: "PHEV_PETROL", label: "Plug-in hybrid Benzin/Elektro" },
  { value: "HEV_DIESEL", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "HEV_PETROL", label: "Voll-Hybrid Benzin/Elektro" },
] as const;

export const utilityExtrasEnum = [
  { value: "8_TYRES", label: "8-fach bereift" },
  { value: "CAR_TRANSPORTER", label: "Autotransporter" },
  { value: "ACCESSIBLE_FOR_DISABLED", label: "Behindertengerecht" },
  { value: "TARPAULIN", label: "Blache/Plane" },
  { value: "DIRECT_IMPORT", label: "Direkt-/Parallelimport" },
  { value: "TAIL_LIFT", label: "Hebebühne" },
  { value: "CRANE", label: "Kran" },
  { value: "REFRIGERATOR", label: "Kühlwagen" },
  { value: "FURNITURE_TRANSPORTER", label: "Möbeltransporter" },
  { value: "SCHOOL_BUS", label: "Schulbus" },
  { value: "WINCH", label: "Seilwinde" },
  { value: "ACCIDENT_VEHICLE", label: "Unfallfahrzeug" },
] as const;
