// ─── Vehicle Types ────────────────────────────────────────────────────────────

export const VEHICLE_TYPES = [
  { value: 'car', label: 'Car' },
  { value: 'camper', label: 'Camper' },
  { value: 'utility', label: 'Utility' },
  { value: 'truck', label: 'Truck' },
] as const;

export type VehicleType = 'car' | 'camper' | 'utility' | 'truck';

// ─── Body Types ───────────────────────────────────────────────────────────────

export const CAR_BODY_TYPES = [
  { value: 'bus', label: 'Bus' },
  { value: 'cabriolet', label: 'Cabriolet' },
  { value: 'coupe', label: 'Coupé' },
  { value: 'small-car', label: 'Kleinwagen' },
  { value: 'estate', label: 'Kombi' },
  { value: 'minivan', label: 'Kompaktvan / Minivan' },
  { value: 'saloon', label: 'Limousine' },
  { value: 'pickup', label: 'Pick-up' },
  { value: 'suv', label: 'SUV / Geländewagen' },
];

export const CAMPER_BODY_TYPES = [
  { value: 'alcove', label: 'Alkoven' },
  { value: 'trailer', label: 'Anhänger' },
  { value: 'bus', label: 'Bus' },
  { value: 'integrated', label: 'Integriertes Wohnmobil' },
  { value: 'cab', label: 'Kabine' },
  { value: 'box', label: 'Kasten' },
  { value: 'estate', label: 'Kombi' },
  { value: 'minivan', label: 'Kompaktvan / Minivan' },
  { value: 'pickup', label: 'Pick-up' },
  { value: 'other', label: 'Sonstige' },
  { value: 'suv', label: 'SUV / Geländewagen' },
  { value: 'semi-integrated', label: 'Teilintegrierter' },
  { value: 'motorhome', label: 'Wohnmobil' },
  { value: 'caravan', label: 'Wohnwagen' },
];

export const UTILITY_BODY_TYPES = [
  { value: 'bridge', label: 'Brücke' },
  { value: 'bridge-double-cab', label: 'Brücke mit Doppelkabine' },
  { value: 'bus', label: 'Bus' },
  { value: 'chassis-cab', label: 'Chassis Kabine' },
  { value: 'box', label: 'Kasten' },
  { value: 'box-glazed', label: 'Kasten verglast' },
  { value: 'box-double-cab', label: 'Kastenwagen Doppelkabine' },
  { value: 'tipper', label: 'Kipper' },
  { value: 'estate', label: 'Kombi' },
  { value: 'minivan', label: 'Kompaktvan / Minivan' },
  { value: 'pickup', label: 'Pick-up' },
  { value: 'platform', label: 'Platform' },
  { value: 'semi-trailer', label: 'Sattel-Auflieger' },
  { value: 'suv', label: 'SUV / Geländewagen' },
];

export const TRUCK_BODY_TYPES = [
  { value: 'bridge', label: 'Brücke' },
  { value: 'chassis-cab', label: 'Chassis Kabine' },
  { value: 'cab-over', label: 'Doppelkabine' },
  { value: 'box', label: 'Kasten' },
  { value: 'tipper', label: 'Kipper' },
  { value: 'car', label: 'Reisebus' },
  { value: 'semi-trailer', label: 'Sattel-Auflieger' },
];

// ─── Fuel Types ───────────────────────────────────────────────────────────────

export const CAR_FUEL_TYPES = [
  { value: 'petrol', label: 'Benzin' },
  { value: 'ethanol-petrol', label: 'Bioethanol' },
  { value: 'diesel', label: 'Diesel' },
  { value: 'electric', label: 'Elektro' },
  { value: 'cng-petrol', label: 'Erdgas (CNG) / Benzin' },
  { value: 'lpg-petrol', label: 'Flüssiggas (LPG) / Benzin' },
  { value: 'mhev-diesel', label: 'Mild-Hybrid Diesel/Elektro' },
  { value: 'mhev-petrol', label: 'Mild-Hybrid Benzin/Elektro' },
  { value: 'phev-diesel', label: 'Plug-in hybrid Diesel/Elektro' },
  { value: 'phev-petrol', label: 'Plug-in hybrid Benzin/Elektro' },
  { value: 'hev-diesel', label: 'Voll-Hybrid Diesel/Elektro' },
  { value: 'hev-petrol', label: 'Voll-Hybrid Benzin/Elektro' },
  { value: 'hydrogen', label: 'Wasserstoff' },
];

export const CAMPER_FUEL_TYPES = [
  { value: 'petrol', label: 'Benzin' },
  { value: 'ethanol-petrol', label: 'Bioethanol' },
  { value: 'diesel', label: 'Diesel' },
  { value: 'electric', label: 'Elektro' },
  { value: 'hev-diesel', label: 'Voll-Hybrid Diesel/Elektro' },
  { value: 'hev-petrol', label: 'Voll-Hybrid Benzin/Elektro' },
];

export const UTILITY_FUEL_TYPES = [
  { value: 'petrol', label: 'Benzin' },
  { value: 'diesel', label: 'Diesel' },
  { value: 'electric', label: 'Elektro' },
  { value: 'cng-petrol', label: 'Erdgas (CNG) / Benzin' },
  { value: 'lpg-petrol', label: 'Flüssiggas (LPG) / Benzin' },
  { value: 'mhev-diesel', label: 'Mild-Hybrid Diesel/Elektro' },
  { value: 'mhev-petrol', label: 'Mild-Hybrid Benzin/Elektro' },
  { value: 'phev-diesel', label: 'Plug-in hybrid Diesel/Elektro' },
  { value: 'phev-petrol', label: 'Plug-in hybrid Benzin/Elektro' },
  { value: 'hev-diesel', label: 'Voll-Hybrid Diesel/Elektro' },
  { value: 'hev-petrol', label: 'Voll-Hybrid Benzin/Elektro' },
];

export const TRUCK_FUEL_TYPES = [
  { value: 'petrol', label: 'Benzin' },
  { value: 'diesel', label: 'Diesel' },
  { value: 'electric', label: 'Elektro' },
];

// ─── Extras ───────────────────────────────────────────────────────────────────

export const CAR_EXTRAS = [
  { value: '8-tyres', label: '8-fach bereift' },
  { value: 'accessible-for-disabled', label: 'Behindertengerecht' },
  { value: 'direct-import', label: 'Direkt-/Parallelimport' },
  { value: 'race-car', label: 'Rennwagen' },
  { value: 'tuning', label: 'Tuning' },
  { value: 'accident-vehicle', label: 'Unfallfahrzeug' },
];

export const CAMPER_EXTRAS = [
  { value: 'accessible-for-disabled', label: 'Behindertengerecht' },
  { value: 'direct-import', label: 'Direkt-/Parallelimport' },
  { value: 'accident-vehicle', label: 'Unfallfahrzeug' },
];

export const UTILITY_EXTRAS = [
  { value: '8-tyres', label: '8-fach bereift' },
  { value: 'car-transporter', label: 'Autotransporter' },
  { value: 'accessible-for-disabled', label: 'Behindertengerecht' },
  { value: 'tarpaulin', label: 'Blache/Plane' },
  { value: 'direct-import', label: 'Direkt-/Parallelimport' },
  { value: 'tail-lift', label: 'Hebebühne' },
  { value: 'crane', label: 'Kran' },
  { value: 'refrigerator', label: 'Kühlwagen' },
  { value: 'furniture-transporter', label: 'Möbeltransporter' },
  { value: 'school-bus', label: 'Schulbus' },
  { value: 'winch', label: 'Seilwinde' },
  { value: 'accident-vehicle', label: 'Unfallfahrzeug' },
];

export const TRUCK_EXTRAS = [
  { value: 'direct-import', label: 'Direkt-/Parallelimport' },
  { value: 'accident-vehicle', label: 'Unfallfahrzeug' },
  { value: 'tarpaulin', label: 'Blache/Plane' },
  { value: 'tail-lift', label: 'Hebebühne' },
];

// ─── Makes (top brands for quick selection) ───────────────────────────────────

export const CAR_TOP_MAKES = [
  { value: 'mercedes', label: 'Mercedes-Benz' },
  { value: 'bmw', label: 'BMW' },
  { value: 'audi', label: 'Audi' },
  { value: 'volkswagen', label: 'Volkswagen' },
  { value: 'porsche', label: 'Porsche' },
  { value: 'ford', label: 'Ford' },
  { value: 'skoda', label: 'Skoda' },
  { value: 'opel', label: 'Opel' },
  { value: 'toyota', label: 'Toyota' },
  { value: 'volvo', label: 'Volvo' },
];

export const CAR_ALL_MAKES = [
  { value: '9ff', label: '9ff' },
  { value: 'abarth', label: 'Abarth' },
  { value: 'ac', label: 'AC' },
  { value: 'acm', label: 'ACM' },
  { value: 'acura', label: 'Acura' },
  { value: 'aerfal', label: 'Aerfal' },
  { value: 'aiways', label: 'Aiways' },
  { value: 'aixam', label: 'Aixam' },
  { value: 'alba-mobility', label: 'Alba Mobility' },
  { value: 'alfa-romeo', label: 'Alfa Romeo' },
  { value: 'alpina', label: 'Alpina' },
  { value: 'alpine', label: 'Alpine' },
  { value: 'amphicar', label: 'Amphicar' },
  { value: 'aston-martin', label: 'Aston Martin' },
  { value: 'aurus', label: 'Aurus' },
  { value: 'austin', label: 'Austin' },
  { value: 'austin-healey', label: 'Austin-Healey' },
  { value: 'autobianchi', label: 'Autobianchi' },
  { value: 'baic', label: 'BAIC' },
  { value: 'bentley', label: 'Bentley' },
  { value: 'bugatti', label: 'Bugatti' },
  { value: 'buick', label: 'Buick' },
  { value: 'byd', label: 'BYD' },
  { value: 'cadillac', label: 'Cadillac' },
  { value: 'caterham', label: 'Caterham' },
  { value: 'chevrolet', label: 'Chevrolet' },
  { value: 'chrysler', label: 'Chrysler' },
  { value: 'citroen', label: 'Citroen' },
  { value: 'cupra', label: 'CUPRA' },
  { value: 'dacia', label: 'Dacia' },
  { value: 'daewoo', label: 'Daewoo' },
  { value: 'daihatsu', label: 'Daihatsu' },
  { value: 'dodge', label: 'Dodge' },
  { value: 'ds-automobiles', label: 'DS Automobiles' },
  { value: 'ferrari', label: 'Ferrari' },
  { value: 'fiat', label: 'Fiat' },
  { value: 'fisker', label: 'Fisker' },
  { value: 'geely', label: 'Geely' },
  { value: 'genesis', label: 'Genesis' },
  { value: 'gmc', label: 'GMC' },
  { value: 'great-wall', label: 'Great Wall' },
  { value: 'gwm', label: 'GWM' },
  { value: 'haval', label: 'Haval' },
  { value: 'honda', label: 'Honda' },
  { value: 'hummer', label: 'HUMMER' },
  { value: 'hyundai', label: 'Hyundai' },
  { value: 'ineos', label: 'Ineos' },
  { value: 'infiniti', label: 'Infiniti' },
  { value: 'isuzu', label: 'Isuzu' },
  { value: 'iveco', label: 'Iveco' },
  { value: 'jaguar', label: 'Jaguar' },
  { value: 'jeep', label: 'Jeep' },
  { value: 'kia', label: 'Kia' },
  { value: 'koenigsegg', label: 'Koenigsegg' },
  { value: 'lada', label: 'Lada' },
  { value: 'lamborghini', label: 'Lamborghini' },
  { value: 'lancia', label: 'Lancia' },
  { value: 'land-rover', label: 'Land Rover' },
  { value: 'leapmotor', label: 'Leapmotor' },
  { value: 'lexus', label: 'Lexus' },
  { value: 'lincoln', label: 'Lincoln' },
  { value: 'lotus', label: 'Lotus' },
  { value: 'lucid', label: 'Lucid' },
  { value: 'lynk-co', label: 'Lynk & Co' },
  { value: 'mahindra', label: 'Mahindra' },
  { value: 'man', label: 'MAN' },
  { value: 'maserati', label: 'Maserati' },
  { value: 'maxus', label: 'Maxus' },
  { value: 'maybach', label: 'Maybach' },
  { value: 'mazda', label: 'Mazda' },
  { value: 'mclaren', label: 'McLaren' },
  { value: 'mg', label: 'MG' },
  { value: 'mini', label: 'MINI' },
  { value: 'mitsubishi', label: 'Mitsubishi' },
  { value: 'morgan', label: 'Morgan' },
  { value: 'nio', label: 'NIO' },
  { value: 'nissan', label: 'Nissan' },
  { value: 'oldsmobile', label: 'Oldsmobile' },
  { value: 'omoda', label: 'Omoda' },
  { value: 'pagani', label: 'Pagani' },
  { value: 'peugeot', label: 'Peugeot' },
  { value: 'polestar', label: 'Polestar' },
  { value: 'pontiac', label: 'Pontiac' },
  { value: 'ram', label: 'RAM' },
  { value: 'rivian', label: 'Rivian' },
  { value: 'rolls-royce', label: 'Rolls-Royce' },
  { value: 'rover', label: 'Rover' },
  { value: 'saab', label: 'Saab' },
  { value: 'seat', label: 'SEAT' },
  { value: 'seres', label: 'Seres' },
  { value: 'smart', label: 'smart' },
  { value: 'ssangyong', label: 'SsangYong' },
  { value: 'subaru', label: 'Subaru' },
  { value: 'suzuki', label: 'Suzuki' },
  { value: 'tata', label: 'Tata' },
  { value: 'tesla', label: 'Tesla' },
  { value: 'togg', label: 'Togg' },
  { value: 'trabant', label: 'Trabant' },
  { value: 'triumph', label: 'Triumph' },
  { value: 'tvr', label: 'TVR' },
  { value: 'uaz', label: 'UAZ' },
  { value: 'vinfast', label: 'VinFast' },
  { value: 'voyah', label: 'Voyah' },
  { value: 'wiesmann', label: 'Wiesmann' },
  { value: 'xiaomi', label: 'Xiaomi' },
  { value: 'xpeng', label: 'Xpeng' },
  { value: 'zeekr', label: 'Zeekr' },
  { value: 'others', label: 'Others' },
];

export const CAMPER_TOP_MAKES = [
  { value: 'adria', label: 'Adria' },
  { value: 'burstner', label: 'Bürstner' },
  { value: 'carado', label: 'Carado' },
  { value: 'dethleffs', label: 'Dethleffs' },
  { value: 'fendt', label: 'Fendt' },
  { value: 'hobby', label: 'Hobby' },
  { value: 'hymer', label: 'Hymer' },
  { value: 'knaus', label: 'Knaus' },
  { value: 'lmc', label: 'LMC' },
  { value: 'sunlight', label: 'Sunlight' },
];

export const CAMPER_ALL_MAKES = [
  { value: 'action-mobil', label: 'Action Mobil' },
  { value: 'airstream', label: 'Airstream' },
  { value: 'auto-sleepers', label: 'Auto-Sleepers' },
  { value: 'autostar', label: 'Autostar' },
  { value: 'benimar', label: 'Benimar' },
  { value: 'bimobil', label: 'Bimobil' },
  { value: 'carthago', label: 'Carthago' },
  { value: 'challenger', label: 'Challenger' },
  { value: 'chausson', label: 'Chausson' },
  { value: 'citroen', label: 'Citroen' },
  { value: 'concorde', label: 'Concorde' },
  { value: 'crosscamp', label: 'Crosscamp' },
  { value: 'dacia', label: 'Dacia' },
  { value: 'dreamer', label: 'Dreamer' },
  { value: 'elnagh', label: 'Elnagh' },
  { value: 'eriba', label: 'Eriba' },
  { value: 'etrusco', label: 'Etrusco' },
  { value: 'eura-mobil', label: 'Eura Mobil' },
  { value: 'fiat', label: 'Fiat' },
  { value: 'fleurette', label: 'Fleurette' },
  { value: 'ford', label: 'Ford' },
  { value: 'frankia', label: 'Frankia' },
  { value: 'giottiline', label: 'Giottiline' },
  { value: 'globecar', label: 'Globecar' },
  { value: 'itineo', label: 'Itineo' },
  { value: 'iveco', label: 'Iveco' },
  { value: 'james-cook', label: 'James Cook' },
  { value: 'kabe', label: 'Kabe' },
  { value: 'karmann', label: 'Karmann' },
  { value: 'la-strada', label: 'La Strada' },
  { value: 'laika', label: 'Laika' },
  { value: 'le-voyageur', label: 'Le Voyageur' },
  { value: 'malibu', label: 'Malibu' },
  { value: 'man', label: 'MAN' },
  { value: 'maxus', label: 'Maxus' },
  { value: 'mclouis', label: 'McLouis' },
  { value: 'mercedes-benz', label: 'Mercedes-Benz' },
  { value: 'mobilvetta', label: 'Mobilvetta' },
  { value: 'morelo', label: 'Morelo' },
  { value: 'niesmann-+-bischoff', label: 'Niesmann + Bischoff' },
  { value: 'nissan', label: 'Nissan' },
  { value: 'opel', label: 'Opel' },
  { value: 'peugeot', label: 'Peugeot' },
  { value: 'phoenix', label: 'Phoenix' },
  { value: 'pilote', label: 'Pilote' },
  { value: 'possl', label: 'Pössl' },
  { value: 'rapido', label: 'Rapido' },
  { value: 'renault', label: 'Renault' },
  { value: 'rimor', label: 'Rimor' },
  { value: 'roadcar', label: 'Roadcar' },
  { value: 'roller-team', label: 'Roller Team' },
  { value: 'scania', label: 'Scania' },
  { value: 'sterckeman', label: 'Sterckeman' },
  { value: 'sun-living', label: 'Sun Living' },
  { value: 'swift', label: 'Swift' },
  { value: 'tabbert', label: 'Tabbert' },
  { value: 'tiffin-motorhomes', label: 'Tiffin Motorhomes' },
  { value: 'toyota', label: 'Toyota' },
  { value: 'trigano', label: 'Trigano' },
  { value: 'vantourer', label: 'Vantourer' },
  { value: 'vw', label: 'VW' },
  { value: 'weinsberg', label: 'Weinsberg' },
  { value: 'westfalia', label: 'Westfalia' },
  { value: 'wingamm', label: 'Wingamm' },
  { value: 'winnebago', label: 'Winnebago' },
];

export const UTILITY_TOP_MAKES = [
  { value: 'fiat', label: 'Fiat' },
  { value: 'ford', label: 'Ford' },
  { value: 'iveco', label: 'Iveco' },
  { value: 'man', label: 'MAN' },
  { value: 'mercedes-benz', label: 'Mercedes-Benz' },
  { value: 'nissan', label: 'Nissan' },
  { value: 'peugeot', label: 'Peugeot' },
  { value: 'renault', label: 'Renault' },
  { value: 'toyota', label: 'Toyota' },
  { value: 'vw', label: 'VW' },
];

export const UTILITY_ALL_MAKES = [
  { value: 'byd', label: 'BYD' },
  { value: 'cenntro', label: 'Cenntro' },
  { value: 'chevrolet', label: 'Chevrolet' },
  { value: 'citroen', label: 'Citroen' },
  { value: 'dacia', label: 'Dacia' },
  { value: 'daihatsu', label: 'Daihatsu' },
  { value: 'dfsk', label: 'DFSK' },
  { value: 'dodge', label: 'Dodge' },
  { value: 'elaris', label: 'Elaris' },
  { value: 'gac-gonow', label: 'Gac Gonow' },
  { value: 'gaz', label: 'GAZ' },
  { value: 'gmc', label: 'GMC' },
  { value: 'honda', label: 'Honda' },
  { value: 'hyundai', label: 'Hyundai' },
  { value: 'ineos', label: 'Ineos' },
  { value: 'isuzu', label: 'Isuzu' },
  { value: 'jac', label: 'JAC' },
  { value: 'jeep', label: 'Jeep' },
  { value: 'kia', label: 'Kia' },
  { value: 'land-rover', label: 'Land Rover' },
  { value: 'levc', label: 'LEVC' },
  { value: 'maxus', label: 'Maxus' },
  { value: 'mazda', label: 'Mazda' },
  { value: 'mini', label: 'Mini' },
  { value: 'mitsubishi', label: 'Mitsubishi' },
  { value: 'mitsubishi-fuso', label: 'Mitsubishi Fuso' },
  { value: 'opel', label: 'Opel' },
  { value: 'piaggio', label: 'Piaggio' },
  { value: 'puch', label: 'Puch' },
  { value: 'seat', label: 'SEAT' },
  { value: 'skoda', label: 'Skoda' },
  { value: 'sokon', label: 'Sokon' },
  { value: 'streetscooter', label: 'Streetscooter' },
  { value: 'suzuki', label: 'Suzuki' },
  { value: 'tata', label: 'Tata' },
  { value: 'unimog', label: 'Unimog' },
  { value: 'vem', label: 'VEM' },
];

export const TRUCK_TOP_MAKES = [
  { value: 'daf', label: 'DAF' },
  { value: 'ford-trucks', label: 'Ford Trucks' },
  { value: 'iveco', label: 'Iveco' },
  { value: 'man', label: 'MAN' },
  { value: 'mercedes-benz', label: 'Mercedes-Benz' },
  { value: 'renault', label: 'Renault' },
  { value: 'scania', label: 'Scania' },
  { value: 'volvo', label: 'Volvo' },
];

export const TRUCK_ALL_MAKES = [
  { value: 'byd', label: 'BYD' },
  { value: 'cenntro', label: 'Cenntro' },
  { value: 'fbw', label: 'FBW' },
  { value: 'fendt', label: 'Fendt' },
  { value: 'ford', label: 'Ford' },
  { value: 'fuso', label: 'Fuso' },
  { value: 'hanomag', label: 'Hanomag' },
  { value: 'iveco-magirus', label: 'Iveco (Magirus)' },
  { value: 'kaessbohrer', label: 'Kaessbohrer' },
  { value: 'man-vw', label: 'MAN - VW' },
  { value: 'mitsubishi', label: 'Mitsubishi' },
  { value: 'nissan', label: 'Nissan' },
  { value: 'santana', label: 'Santana' },
  { value: 'saurer', label: 'Saurer' },
  { value: 'setra', label: 'Setra' },
  { value: 'steyr', label: 'Steyr' },
  { value: 'tatra', label: 'Tatra' },
  { value: 'toyota', label: 'Toyota' },
  { value: 'unimog', label: 'Unimog' },
  { value: 'vw', label: 'VW' },
];
