export const camperMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "adria", label: "Adria" },
      { value: "burstner", label: "Bürstner" },
      { value: "carado", label: "Carado" },
      { value: "dethleffs", label: "Dethleffs" },
      { value: "fendt", label: "Fendt" },
      { value: "hobby", label: "Hobby" },
      { value: "hymer", label: "Hymer" },
      { value: "knaus", label: "Knaus" },
      { value: "lmc", label: "LMC" },
      { value: "sunlight", label: "Sunlight" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "action-mobil", label: "Action Mobil" },
      { value: "adventurer", label: "Adventurer" },
      { value: "aero-one", label: "Aero One" },
      { value: "aero-plast", label: "Aero Plast" },
      { value: "ahorn", label: "Ahorn" },
      { value: "airstream", label: "Airstream" },
      { value: "arca", label: "Arca" },
      { value: "auto-sleepers", label: "Auto-Sleepers" },
      { value: "autostar", label: "Autostar" },
      { value: "avanti", label: "Avanti" },
      { value: "azalai", label: "Azalai" },
      { value: "bantam", label: "Bantam" },
      { value: "baskent-karavan", label: "Baskent Karavan" },
      { value: "bavaria", label: "Bavaria" },
      { value: "bavariacamp", label: "Bavariacamp" },
      { value: "beauer", label: "Beauer" },
      { value: "bedford", label: "Bedford" },
      { value: "benimar", label: "Benimar" },
      { value: "berkshire", label: "Berkshire" },
      { value: "billys", label: "Billys" },
      { value: "bimobil", label: "Bimobil" },
      { value: "bison", label: "Bison" },
      { value: "blucamp", label: "Blucamp" },
      { value: "bocklet", label: "Bocklet" },
      { value: "bravia", label: "Bravia" },
      { value: "bremach", label: "Bremach" },
      { value: "bucher", label: "Bucher" },
      { value: "bunkervan", label: "Bunkervan" },
      { value: "burow", label: "Burow" },
      { value: "callau", label: "Callau" },
      { value: "camp-let", label: "Camp-Let" },
      { value: "camppass", label: "Camppass" },
      { value: "capra-camper", label: "Capra Camper" },
      { value: "caravelair", label: "Caravelair" },
      { value: "caretta", label: "Caretta" },
      { value: "carthago", label: "Carthago" },
      { value: "challenger", label: "Challenger" },
      { value: "chausson", label: "Chausson" },
      { value: "chevrolet", label: "Chevrolet" },
      { value: "ci-caravansinternational", label: "CI Caravansinternational" },
      { value: "citroen", label: "Citroen" },
      { value: "clever-vans", label: "Clever Vans" },
      { value: "coachmen", label: "Coachmen" },
      { value: "comanche", label: "Comanche" },
      { value: "concorde", label: "Concorde" },
      { value: "conqueror-companion", label: "Conqueror Companion" },
      { value: "constructam", label: "Constructam" },
      { value: "cramer-technik", label: "Cramer Technik" },
      { value: "crawler", label: "Crawler" },
      { value: "cristal", label: "Cristal" },
      { value: "crosscamp", label: "Crosscamp" },
      { value: "crossroad", label: "Crossroad" },
      { value: "cs-reisemobile", label: "CS-Reisemobile" },
      { value: "dacia", label: "Dacia" },
      { value: "daf", label: "DAF" },
      { value: "daimler", label: "Daimler" },
      { value: "daltec", label: "Daltec" },
      { value: "damon", label: "Damon" },
      { value: "dehler", label: "Dehler" },
      { value: "dodge", label: "Dodge" },
      { value: "dovra", label: "Dovra" },
      { value: "dreamer", label: "Dreamer" },
      { value: "due-erre", label: "Due Erre" },
      { value: "duss", label: "Duss" },
      { value: "dux", label: "Dux" },
      { value: "eagle-ridge", label: "Eagle Ridge" },
      { value: "easy-caravanning", label: "Easy Caravanning" },
      { value: "eiffelland", label: "Eiffelland" },
      { value: "elnagh", label: "Elnagh" },
      { value: "erba-karavan", label: "Erba Karavan" },
      { value: "eriba", label: "Eriba" },
      { value: "esterel", label: "Esterel" },
      { value: "etrusco", label: "Etrusco" },
      { value: "eura-mobil", label: "Eura Mobil" },
      { value: "euroliner-workhorse", label: "Euroliner / Workhorse" },
      { value: "evergreen", label: "Evergreen" },
      { value: "f-kon", label: "F-Kon" },
      { value: "fama-schmidt", label: "Fama Schmidt" },
      { value: "ffb", label: "FFB" },
      { value: "fiat", label: "Fiat" },
      { value: "flagstaff", label: "Flagstaff" },
      { value: "fleetwood", label: "Fleetwood" },
      { value: "fleurette", label: "Fleurette" },
      { value: "font-vendome", label: "Font Vendome" },
      { value: "ford", label: "Ford" },
      { value: "forrest-river", label: "Forrest River" },
      { value: "forster", label: "Forster" },
      { value: "four-winds-international", label: "Four Winds International" },
      { value: "frankia", label: "Frankia" },
      { value: "freightliner", label: "Freightliner" },
      { value: "gaz", label: "GAZ" },
      { value: "geocamper", label: "Geocamper" },
      { value: "giottiline", label: "Giottiline" },
      { value: "glendale-rv", label: "Glendale RV" },
      { value: "globe-traveller", label: "Globe-Traveller" },
      { value: "globecar", label: "Globecar" },
      { value: "gmc", label: "GMC" },
      { value: "grand-design", label: "Grand Design" },
      { value: "hanroad", label: "Hanroad" },
      { value: "hehn-mobil", label: "Hehn Mobil" },
      { value: "herocamper", label: "Herocamper" },
      { value: "holiday-rambler", label: "Holiday Rambler" },
      { value: "home-car", label: "Home-Car" },
      { value: "hotomobil", label: "Hotomobil" },
      { value: "hunter-nature", label: "Hunter Nature" },
      { value: "hyundai", label: "Hyundai" },
      { value: "ilusion", label: "Ilusion" },
      { value: "impression", label: "Impression" },
      { value: "international", label: "International" },
      { value: "isuzu", label: "Isuzu" },
      { value: "itineo", label: "Itineo" },
      { value: "iveco", label: "Iveco" },
      { value: "james-cook", label: "James Cook" },
      { value: "jeep", label: "Jeep" },
      { value: "joint", label: "Joint" },
      { value: "kabe", label: "Kabe" },
      { value: "kaiser", label: "Kaiser" },
      { value: "karmann", label: "Karmann" },
      { value: "kempf", label: "Kempf" },
      { value: "kentucky", label: "Kentucky" },
      { value: "la-strada", label: "La Strada" },
      { value: "laika", label: "Laika" },
      { value: "land-rover", label: "Land Rover" },
      { value: "lander", label: "Lander" },
      { value: "lapp-expeditionstrailer", label: "Lapp Expeditionstrailer" },
      { value: "le-voyageur", label: "Le Voyageur" },
      { value: "lsc", label: "LSC" },
      { value: "lume", label: "Lume" },
      { value: "lume-traveler", label: "Lume Traveler" },
      { value: "malibu", label: "Malibu" },
      { value: "man", label: "MAN" },
      { value: "martin", label: "Martin" },
      { value: "maurer", label: "Maurer" },
      { value: "maxus", label: "Maxus" },
      { value: "mazda", label: "Mazda" },
      { value: "mclouis", label: "McLouis" },
      { value: "mega-mobil", label: "Mega Mobil" },
      { value: "mercedes-benz", label: "Mercedes-Benz" },
      { value: "metalian", label: "Metalian" },
      { value: "miller", label: "Miller" },
      { value: "mini-freestyle", label: "Mini-Freestyle" },
      { value: "miniatouring", label: "Miniatouring" },
      { value: "mink", label: "Mink" },
      { value: "mirage", label: "Mirage" },
      { value: "mitsubishi", label: "Mitsubishi" },
      { value: "mkp", label: "MKP" },
      { value: "mobilvetta", label: "Mobilvetta" },
      { value: "monaco", label: "Monaco" },
      { value: "moncayo", label: "Moncayo" },
      { value: "mooblehouse", label: "Mooblehouse" },
      { value: "mooveo", label: "Mooveo" },
      { value: "morelo", label: "Morelo" },
      { value: "nagetusch", label: "Nagetusch" },
      { value: "newmar", label: "Newmar" },
      { value: "niesmann-+-bischoff", label: "Niesmann + Bischoff" },
      { value: "niewiadow", label: "Niewiadow" },
      { value: "nissan", label: "Nissan" },
      { value: "nobelart", label: "Nobelart" },
      { value: "nordlight-camper", label: "Nordlight Camper" },
      { value: "notin", label: "Notin" },
      { value: "opel", label: "Opel" },
      { value: "orangecamp", label: "Orangecamp" },
      { value: "ormo", label: "Ormo" },
      { value: "palomino", label: "Palomino" },
      { value: "panama", label: "Panama" },
      { value: "papillon", label: "Papillon" },
      { value: "peugeot", label: "Peugeot" },
      { value: "phoenix", label: "Phoenix" },
      { value: "pilote", label: "Pilote" },
      { value: "pla", label: "PLA" },
      { value: "polar", label: "Polar" },
      { value: "possl", label: "Pössl" },
      { value: "procamp", label: "Procamp" },
      { value: "puch", label: "Puch" },
      { value: "randger", label: "Randger" },
      { value: "rapido", label: "Rapido" },
      { value: "rausschwarmer", label: "Rausschwärmer" },
      { value: "reflection", label: "Reflection" },
      { value: "renault", label: "Renault" },
      { value: "rexhall", label: "Rexhall" },
      { value: "rhon-camp", label: "Rhön Camp" },
      { value: "rimor", label: "Rimor" },
      { value: "riviera", label: "Riviera" },
      { value: "rl-mobile", label: "RL-Mobile" },
      { value: "rmb", label: "RMB" },
      { value: "roadcar", label: "Roadcar" },
      { value: "robel-mobil", label: "Robel Mobil" },
      { value: "robeta", label: "Robeta" },
      { value: "rocket-caravans", label: "Rocket Caravans" },
      { value: "rockwood", label: "Rockwood" },
      { value: "roller-team", label: "Roller Team" },
      { value: "saly", label: "Saly" },
      { value: "saurer", label: "Saurer" },
      { value: "scania", label: "Scania" },
      { value: "scanvogn", label: "Scanvogn" },
      { value: "schwabenmobil", label: "Schwabenmobil" },
      { value: "sea", label: "Sea" },
      { value: "sealander", label: "Sealander" },
      { value: "setra", label: "Setra" },
      { value: "silver", label: "Silver" },
      { value: "skyline", label: "Skyline" },
      { value: "solifer", label: "Solifer" },
      { value: "sprite", label: "Sprite" },
      { value: "starcraft", label: "Starcraft" },
      { value: "starliner", label: "Starliner" },
      { value: "sterckeman", label: "Sterckeman" },
      { value: "steyr", label: "Steyr" },
      { value: "stylevan", label: "Stylevan" },
      { value: "sun-living", label: "Sun Living" },
      { value: "swift", label: "Swift" },
      { value: "swiss-compact", label: "Swiss Compact" },
      { value: "tabbert", label: "Tabbert" },
      { value: "tartaruga", label: "Tartaruga" },
      { value: "taurus", label: "Taurus" },
      { value: "tec", label: "TEC" },
      { value: "tempo", label: "Tempo" },
      { value: "thomson", label: "Thomson" },
      { value: "tiffin-motorhomes", label: "Tiffin Motorhomes" },
      { value: "tikro", label: "Tikro" },
      { value: "tischer", label: "Tischer" },
      { value: "tourne-mobil", label: "Tourne Mobil" },
      { value: "toyota", label: "Toyota" },
      { value: "travel-supreme", label: "Travel Supreme" },
      { value: "trigano", label: "Trigano" },
      { value: "turatello", label: "Turatello" },
      { value: "val-de-loire", label: "Val de Loire" },
      { value: "valeur", label: "Valeur" },
      { value: "van-hool", label: "Van Hool" },
      { value: "vantourer", label: "Vantourer" },
      { value: "vario", label: "Vario" },
      { value: "vfw", label: "VFW" },
      { value: "vl-outdoor", label: "VL Outdoor" },
      { value: "volkner", label: "Volkner" },
      { value: "vw", label: "VW" },
      { value: "walde", label: "Walde" },
      { value: "weinsberg", label: "Weinsberg" },
      { value: "weippert", label: "Weippert" },
      { value: "westfalia", label: "Westfalia" },
      { value: "wilk", label: "Wilk" },
      { value: "wingamm", label: "Wingamm" },
      { value: "winnebago", label: "Winnebago" },
      { value: "wm-meyer", label: "WM Meyer" },
      { value: "wochner", label: "Wochner" },
      { value: "xgo", label: "XGO" },
      { value: "yucon", label: "Yucon" },
    ],
  },
] as const;

export const camperBodyTypeEnum = [
  { value: "alcove", label: "Alkoven" },
  { value: "trailer", label: "Anhänger" },
  { value: "bus", label: "Bus" },
  { value: "integrated", label: "Integriertes Wohnmobil" },
  { value: "cab", label: "Kabine" },
  { value: "box", label: "Kasten" },
  { value: "estate", label: "Kombi" },
  { value: "minivan", label: "Kompaktvan / Minivan" },
  { value: "pickup", label: "Pick-up" },
  { value: "other", label: "Sonstige" },
  { value: "suv", label: "SUV / Geländewagen" },
  { value: "semi-integrated", label: "Teilintegrierter" },
  { value: "motorhome", label: "Wohnmobil" },
  { value: "caravan", label: "Wohnwagen" },
] as const;

export const camperFuelTypeEnum = [
  { value: "petrol", label: "Benzin" },
  { value: "ethanol-petrol", label: "Bioethanol" },
  { value: "diesel", label: "Diesel" },
  { value: "electric", label: "Elektro" },
  { value: "hev-diesel", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "hev-petrol", label: "Voll-Hybrid Benzin/Elektro" },
] as const;

export const camperExtrasEnum = [
  { value: "accessible-for-disabled", label: "Behindertengerecht" },
  { value: "direct-import", label: "Direkt-/Parallelimport" },
  { value: "accident-vehicle", label: "Unfallfahrzeug" },
] as const;
