export const utilityMakes = [
  {
    label: "Top-Marken",
    items: [
      { value: "fiat", label: "Fiat" },
      { value: "ford", label: "Ford" },
      { value: "iveco", label: "Iveco" },
      { value: "man", label: "MAN" },
      { value: "mercedes-benz", label: "Mercedes-Benz" },
      { value: "nissan", label: "Nissan" },
      { value: "peugeot", label: "Peugeot" },
      { value: "renault", label: "Renault" },
      { value: "toyota", label: "Toyota" },
      { value: "vw", label: "VW" },
    ],
  },
  {
    label: "Alle Marken",
    items: [
      { value: "ac", label: "AC" },
      { value: "addax-motors", label: "Addax Motors" },
      { value: "aebi", label: "Aebi" },
      { value: "agados", label: "Agados" },
      { value: "alke", label: "Alke" },
      { value: "alvis", label: "Alvis" },
      { value: "autobianchi", label: "Autobianchi" },
      { value: "baw", label: "BAW" },
      { value: "bedford", label: "Bedford" },
      { value: "blyss", label: "Blyss" },
      { value: "bnm", label: "BNM" },
      { value: "bockmann", label: "Böckmann" },
      { value: "boschung", label: "Boschung" },
      { value: "bremach", label: "Bremach" },
      { value: "btalmobil", label: "Btalmobil" },
      { value: "bucher", label: "Bucher" },
      { value: "burstner", label: "Bürstner" },
      { value: "byd", label: "BYD" },
      { value: "cenntro", label: "Cenntro" },
      { value: "chevrolet", label: "Chevrolet" },
      { value: "citroen", label: "Citroen" },
      { value: "dacia", label: "Dacia" },
      { value: "daihatsu", label: "Daihatsu" },
      { value: "daltec", label: "Daltec" },
      { value: "deutz-fahr", label: "Deutz-Fahr" },
      { value: "dfm", label: "DFM" },
      { value: "dfsk", label: "DFSK" },
      { value: "disalcar", label: "Disalcar" },
      { value: "dkw", label: "DKW" },
      { value: "dodge", label: "Dodge" },
      { value: "elaris", label: "Elaris" },
      { value: "equi-trek", label: "Equi-Trek" },
      { value: "evitalia", label: "Evitalia" },
      { value: "fbw", label: "FBW" },
      { value: "fitzel", label: "Fitzel" },
      { value: "forthing", label: "Forthing" },
      { value: "fuso", label: "Fuso" },
      { value: "gac-gonow", label: "Gac Gonow" },
      { value: "gaz", label: "GAZ" },
      { value: "giotti-victoria", label: "Giotti Victoria" },
      { value: "gladiator", label: "Gladiator" },
      { value: "gmc", label: "GMC" },
      { value: "goupil", label: "Goupil" },
      { value: "hanomag", label: "Hanomag" },
      { value: "hobby", label: "Hobby" },
      { value: "honda", label: "Honda" },
      { value: "hrb", label: "HRB" },
      { value: "hudson", label: "Hudson" },
      { value: "humbaur", label: "Humbaur" },
      { value: "hyundai", label: "Hyundai" },
      { value: "ifor", label: "Ifor" },
      { value: "ineos", label: "Ineos" },
      { value: "international", label: "International" },
      { value: "isuzu", label: "Isuzu" },
      { value: "jac", label: "JAC" },
      { value: "jeep", label: "Jeep" },
      { value: "jiayuan", label: "Jiayuan" },
      { value: "john-deere", label: "John Deere" },
      { value: "kaessbohrer", label: "Kaessbohrer" },
      { value: "karmann", label: "Karmann" },
      { value: "kgm-ssangyong", label: "KGM-SsangYong" },
      { value: "kia", label: "Kia" },
      { value: "klingler", label: "Klingler" },
      { value: "ladog", label: "Ladog" },
      { value: "lancia", label: "Lancia" },
      { value: "land-rover", label: "Land Rover" },
      { value: "levc", label: "LEVC" },
      { value: "lincoln", label: "Lincoln" },
      { value: "lindner", label: "Lindner" },
      { value: "maxus", label: "Maxus" },
      { value: "mazda", label: "Mazda" },
      { value: "mega", label: "Mega" },
      { value: "meili", label: "Meili" },
      { value: "mini", label: "Mini" },
      { value: "mitsubishi", label: "Mitsubishi" },
      { value: "mitsubishi-fuso", label: "Mitsubishi Fuso" },
      { value: "mlt", label: "MLT" },
      { value: "morris", label: "Morris" },
      { value: "mowag", label: "Mowag" },
      { value: "om", label: "OM" },
      { value: "opel", label: "Opel" },
      { value: "piaggio", label: "Piaggio" },
      { value: "pinzgauer", label: "Pinzgauer" },
      { value: "pony", label: "Pony" },
      { value: "puch", label: "Puch" },
      { value: "ravo", label: "Ravo" },
      { value: "rolba", label: "Rolba" },
      { value: "ruska", label: "Ruska" },
      { value: "santana", label: "Santana" },
      { value: "saris", label: "Saris" },
      { value: "saurer", label: "Saurer" },
      { value: "schwarzmuller", label: "Schwarzmüller" },
      { value: "seat", label: "SEAT" },
      { value: "setra", label: "Setra" },
      { value: "skoda", label: "Skoda" },
      { value: "sokon", label: "Sokon" },
      { value: "solis", label: "Solis" },
      { value: "steyr", label: "Steyr" },
      { value: "streetscooter", label: "Streetscooter" },
      { value: "stussi", label: "Stüssi" },
      { value: "suzuki", label: "Suzuki" },
      { value: "tata", label: "Tata" },
      { value: "tatra", label: "Tatra" },
      { value: "tempo", label: "Tempo" },
      { value: "tgb", label: "TGB" },
      { value: "tropos", label: "Tropos" },
      { value: "tyn-e", label: "TYN-e" },
      { value: "uaz", label: "UAZ" },
      { value: "unimog", label: "Unimog" },
      { value: "van-hool", label: "Van Hool" },
      { value: "vem", label: "VEM" },
      { value: "walde", label: "Walde" },
      { value: "weijer-w1", label: "Weijer W1" },
      { value: "willys", label: "Willys" },
      { value: "wm-meyer", label: "WM Meyer" },
      { value: "zbinden", label: "Zbinden" },
    ],
  },
] as const;

export const utilityModels: Record<string, { value: string; label: string }[]> =
  {
    byd: [
      { value: "etm6", label: "ETM6" },
      { value: "etp3", label: "ETP3" },
      { value: "t3", label: "T3" },
    ],
    boschung: [{ value: "pony-p4-t", label: "Pony P4-T" }],
    cenntro: [
      { value: "logistar-100", label: "Logistar 100" },
      { value: "logistar-200", label: "Logistar 200" },
      { value: "logistar-260", label: "Logistar 260" },
      { value: "metro", label: "Metro" },
      { value: "teemak", label: "Teemak" },
    ],
    chevrolet: [
      { value: "astro", label: "Astro" },
      { value: "blazer", label: "Blazer" },
      { value: "c-k-pickup", label: "C/K Pickup" },
      { value: "express", label: "Express" },
      { value: "g-van", label: "G-Van" },
    ],
    dacia: [
      { value: "dokker", label: "Dokker" },
      { value: "logan", label: "Logan" },
    ],
    daihatsu: [
      { value: "cab-van-pick", label: "Cab Van/Pick" },
      { value: "hijet", label: "Hijet" },
      { value: "rocky", label: "Rocky" },
    ],
    dfsk: [
      { value: "c-serie", label: "C-Serie" },
      { value: "k-serie", label: "K-Serie" },
      { value: "v-serie", label: "V-Serie" },
    ],
    elaris: [{ value: "caro", label: "Caro" }],
    fiat: [
      { value: "doblo", label: "Doblo" },
      { value: "ducato", label: "Ducato" },
      { value: "fiorino", label: "Fiorino" },
      { value: "fullback", label: "Fullback" },
      { value: "panda-van", label: "Panda Van" },
      { value: "scudo", label: "Scudo" },
      { value: "strada", label: "Strada" },
      { value: "talento", label: "Talento" },
    ],
    forthing: [{ value: "6", label: "6" }],
    "giotti-victoria": [{ value: "gladiator", label: "Gladiator" }],
    gladiator: [{ value: "kipper", label: "Kipper" }],
    gmc: [
      { value: "canyon", label: "Canyon" },
      { value: "savana", label: "Savana" },
      { value: "sierra", label: "Sierra" },
    ],
    honda: [
      { value: "acty", label: "Acty" },
      { value: "ridgeline", label: "Ridgeline" },
    ],
    hyundai: [
      { value: "h-1", label: "H-1" },
      { value: "h-100", label: "H 100" },
      { value: "h-350", label: "H 350" },
      { value: "satellite", label: "Satellite" },
    ],
    ineos: [{ value: "grenadier", label: "Grenadier" }],
    isuzu: [
      { value: "btfs", label: "BTFS" },
      { value: "d-max", label: "D-MAX" },
      { value: "kb-campo", label: "KB/CAMPO" },
      { value: "m21", label: "M21" },
      { value: "m27", label: "M27" },
      { value: "midi", label: "Midi" },
      { value: "n-evo", label: "N-EVO" },
      { value: "nkr", label: "NKR" },
      { value: "nkr-77", label: "NKR 77" },
      { value: "nkr-85", label: "NKR 85" },
      { value: "nlr-85", label: "NLR 85" },
      { value: "nlr-85a", label: "NLR 85A" },
      { value: "nlr-87", label: "NLR 87" },
      { value: "nmr-85", label: "NMR 85" },
      { value: "nnr-85", label: "NNR 85" },
      { value: "nnr-87", label: "NNR 87" },
      { value: "npr-75", label: "NPR 75" },
      { value: "npr-77", label: "NPR 77" },
      { value: "npr-85", label: "NPR 85" },
      { value: "obd-d-n-l35", label: "OBD-D N-L35" },
      { value: "obd-d-n-m55", label: "OBD-D N-M55" },
      { value: "obd-d-n-n35", label: "OBD-D N-N35" },
      { value: "obd-d-n-p65", label: "OBD-D N-P65" },
      { value: "obd-d-n-p75", label: "OBD-D N-P75" },
      { value: "obd-e", label: "OBD-E" },
      { value: "tfs-85", label: "TFS 85" },
      { value: "wfr", label: "WFR" },
      { value: "wfs", label: "WFS" },
    ],
    iveco: [
      { value: "50-10-35", label: "50-10/35" },
      { value: "daily", label: "Daily" },
      { value: "daily-city", label: "Daily City" },
      { value: "e-daily", label: "E Daily" },
      { value: "ecodaily", label: "Ecodaily" },
      { value: "massif", label: "Massif" },
      { value: "turbo-daily", label: "Turbo-Daily" },
    ],
    jac: [
      { value: "m3ev", label: "M3EV" },
      { value: "t8-pro", label: "T8 Pro" },
      { value: "t9ev-4x4", label: "T9EV 4x4" },
    ],
    jeep: [{ value: "gladiator", label: "Gladiator" }],
    kaessbohrer: [{ value: "setra-s9a", label: "Setra S9A" }],
    "kgm-ssangyong": [{ value: "musso", label: "Musso" }],
    kia: [
      { value: "k2500", label: "K2500" },
      { value: "k2900", label: "K2900" },
      { value: "pregio", label: "Pregio" },
      { value: "pregio-ii", label: "Pregio II" },
      { value: "pv5", label: "PV5" },
    ],
    lancia: [{ value: "z-turbo", label: "Z Turbo" }],
    "land-rover": [
      { value: "88-110", label: "88 - 110" },
      { value: "defender", label: "Defender" },
    ],
    levc: [
      { value: "tx", label: "TX" },
      { value: "vn", label: "VN" },
    ],
    man: [{ value: "tge", label: "TGE" }],
    maxus: [
      { value: "deliver-7", label: "Deliver 7" },
      { value: "deliver-9", label: "Deliver 9" },
      { value: "edeliver-3", label: "eDeliver 3" },
      { value: "edeliver-5", label: "eDeliver 5" },
      { value: "edeliver-7", label: "eDeliver 7" },
      { value: "edeliver-9", label: "eDeliver 9" },
      { value: "eterron-9", label: "eTerron 9" },
      { value: "euniq-6", label: "eUniq 6" },
      { value: "ev80", label: "EV80" },
      { value: "t60", label: "T60" },
      { value: "t90-ev", label: "T90 EV" },
    ],
    mazda: [
      { value: "b-2500", label: "B 2500" },
      { value: "bt-50", label: "BT-50" },
      { value: "e-1600", label: "E 1600" },
      { value: "e-2000", label: "E 2000" },
      { value: "e-2200", label: "E 2200" },
    ],
    mega: [{ value: "mega", label: "Mega" }],
    "mercedes-benz": [
      { value: "100-series", label: "100 Series" },
      { value: "200-series", label: "200-Series" },
      { value: "215", label: "215" },
      { value: "218", label: "218" },
      { value: "224", label: "224" },
      { value: "300-series", label: "300-Series" },
      { value: "313", label: "313" },
      { value: "314-cdi", label: "314 CDI" },
      { value: "400-series", label: "400-Series" },
      { value: "411", label: "411" },
      { value: "414", label: "414" },
      { value: "500-series", label: "500-Series" },
      { value: "509", label: "509" },
      { value: "511", label: "511" },
      { value: "515", label: "515" },
      { value: "524", label: "524" },
      { value: "600-series", label: "600-Series" },
      { value: "616", label: "616" },
      { value: "citan", label: "Citan" },
      { value: "e-22-bus", label: "E 2.2 Bus" },
      { value: "ecitan", label: "eCitan" },
      { value: "eqv-300", label: "EQV 300" },
      { value: "marco-polo", label: "Marco Polo" },
      { value: "sprinter", label: "Sprinter" },
      { value: "t-class", label: "T-Class" },
      { value: "viano", label: "Viano" },
      { value: "vito", label: "Vito" },
      { value: "x-220", label: "X 220" },
      { value: "x-250", label: "X 250" },
      { value: "x-350", label: "X 350" },
    ],
    mini: [{ value: "clubvan", label: "Clubvan" }],
    "mitsubishi-fuso": [{ value: "canter", label: "Canter" }],
    mitsubishi: [
      { value: "canter", label: "Canter" },
      { value: "l-200", label: "L 200" },
      { value: "l-300", label: "L 300" },
      { value: "l-400", label: "L 400" },
    ],
    nissan: [
      { value: "atleon", label: "Atleon" },
      { value: "cabstar", label: "Cabstar" },
      { value: "cabstar-e", label: "Cabstar E" },
      { value: "e-nv200", label: "e-NV200" },
      { value: "interstar", label: "Interstar" },
      { value: "king-double", label: "King-/Double" },
      { value: "kubistar", label: "Kubistar" },
      { value: "navara", label: "Navara" },
      { value: "np300-pickup", label: "NP300 Pickup" },
      { value: "nv200", label: "NV200" },
      { value: "nv250", label: "NV250" },
      { value: "nv300", label: "NV300" },
      { value: "nv400", label: "NV400" },
      { value: "primastar", label: "Primastar" },
      { value: "sunny", label: "Sunny" },
      { value: "townstar", label: "Townstar" },
      { value: "trade", label: "Trade" },
      { value: "urvan", label: "Urvan" },
      { value: "vanette", label: "Vanette" },
    ],
    opel: [
      { value: "blitz", label: "Blitz" },
      { value: "campo", label: "Campo" },
      { value: "combo", label: "Combo" },
      { value: "insignia", label: "Insignia" },
      { value: "movano", label: "Movano" },
      { value: "rekord", label: "Rekord" },
      { value: "vivaro", label: "Vivaro" },
      { value: "zafira", label: "Zafira" },
    ],
    peugeot: [
      { value: "bipper", label: "Bipper" },
      { value: "boxer", label: "Boxer" },
      { value: "e-expert", label: "E-Expert" },
      { value: "e-partner", label: "E-Partner" },
      { value: "expert", label: "Expert" },
      { value: "j-9", label: "J 9" },
      { value: "j5", label: "J5" },
      { value: "partner", label: "Partner" },
      { value: "traveller", label: "Traveller" },
    ],
    piaggio: [
      { value: "ape", label: "Ape" },
      { value: "maxxi", label: "Maxxi" },
      { value: "porter", label: "Porter" },
      { value: "quargo", label: "Quargo" },
    ],
    puch: [
      { value: "290", label: "290" },
      { value: "haflinger", label: "Haflinger" },
    ],
    renault: [
      { value: "4-f", label: "4 F" },
      { value: "alaskan", label: "Alaskan" },
      { value: "b-120", label: "B 120" },
      { value: "b-90", label: "B 90" },
      { value: "express", label: "Express" },
      { value: "kangoo", label: "Kangoo" },
      { value: "kangoo-comp", label: "Kangoo Comp." },
      { value: "kangoo-expr", label: "Kangoo Expr." },
      { value: "kangoo-maxi", label: "Kangoo Maxi" },
      { value: "mascott", label: "Mascott" },
      { value: "master", label: "Master" },
      { value: "maxity", label: "Maxity" },
      { value: "messenger", label: "Messenger" },
      { value: "trafic", label: "Trafic" },
      { value: "twizy", label: "Twizy" },
    ],
    seat: [
      { value: "inca", label: "Inca" },
      { value: "terra", label: "Terra" },
    ],
    skoda: [
      { value: "135-136", label: "135 / 136" },
      { value: "praktik", label: "Praktik" },
    ],
    sokon: [{ value: "mini-truck", label: "Mini Truck" }],
    streetscooter: [
      { value: "work-box", label: "Work Box" },
      { value: "work-pick-up", label: "Work Pick-Up" },
      { value: "work-pure", label: "Work Pure" },
    ],
    suzuki: [
      { value: "carry", label: "Carry" },
      { value: "nkr-85", label: "NKR 85" },
      { value: "super-carry", label: "Super Carry" },
    ],
    tata: [
      { value: "pick-up", label: "Pick Up" },
      { value: "telcoline", label: "Telcoline" },
    ],
    toyota: [
      { value: "dyna", label: "Dyna" },
      { value: "hi-ace", label: "Hi-Ace" },
      { value: "hi-lux", label: "Hi-Lux" },
      { value: "land-cruiser", label: "Land Cruiser" },
      { value: "landcruiser", label: "Landcruiser" },
      { value: "lite-ace", label: "Lite-Ace" },
      { value: "proace", label: "Proace" },
      { value: "proace-city", label: "Proace City" },
      { value: "proace-max", label: "Proace Max" },
      { value: "proace-verso", label: "Proace Verso" },
      { value: "tacoma", label: "Tacoma" },
    ],
    "tyn-e": [
      { value: "ltx", label: "LTX" },
      { value: "tx1-e", label: "TX1-e" },
      { value: "tx7-e", label: "TX7-e" },
    ],
    vem: [
      { value: "cargo", label: "Cargo" },
      { value: "cover", label: "Cover" },
      { value: "double", label: "Double" },
      { value: "freeze", label: "Freeze" },
      { value: "multi", label: "Multi" },
      { value: "open", label: "Open" },
      { value: "open-ribalt", label: "Open Ribalt." },
      { value: "open-rsu", label: "Open RSU" },
      { value: "people", label: "People" },
    ],
    vw: [
      { value: "amarok", label: "Amarok" },
      { value: "anfibio", label: "Anfibio" },
      { value: "bus", label: "Bus" },
      { value: "caddy", label: "Caddy" },
      { value: "crafter", label: "Crafter" },
      { value: "grand-california", label: "Grand California" },
      { value: "idbuzz", label: "ID.Buzz" },
      { value: "lt", label: "LT" },
      { value: "t1", label: "T1" },
      { value: "t2", label: "T2" },
      { value: "t3", label: "T3" },
      { value: "t4", label: "T4" },
      { value: "t5", label: "T5" },
      { value: "t6", label: "T6" },
      { value: "t61", label: "T6.1" },
      { value: "t7-multivan", label: "T7 Multivan" },
      { value: "taro", label: "Taro" },
      { value: "transporter", label: "Transporter" },
    ],
  };

export const utilityBodyTypeEnum = [
  { value: "bridge", label: "Brücke" },
  { value: "bridge-double-cab", label: "Brücke mit Doppelkabine" },
  { value: "bus", label: "Bus" },
  { value: "chassis-cab", label: "Chassis Kabine" },
  { value: "box", label: "Kasten" },
  { value: "box-glazed", label: "Kasten verglast" },
  { value: "box-double-cab", label: "Kastenwagen Doppelkabine" },
  { value: "tipper", label: "Kipper" },
  { value: "estate", label: "Kombi" },
  { value: "minivan", label: "Kompaktvan / Minivan" },
  { value: "pickup", label: "Pick-up" },
  { value: "platform", label: "Platform" },
  { value: "semi-trailer", label: "Sattel-Auflieger" },
  { value: "suv", label: "SUV / Geländewagen" },
] as const;

export const utilityFuelTypeEnum = [
  { value: "petrol", label: "Benzin" },
  { value: "diesel", label: "Diesel" },
  { value: "electric", label: "Elektro" },
  { value: "cng-petrol", label: "Erdgas (CNG) / Benzin" },
  { value: "lpg-petrol", label: "Flüssiggas (LPG) / Benzin" },
  { value: "mhev-diesel", label: "Mild-Hybrid Diesel/Elektro" },
  { value: "mhev-petrol", label: "Mild-Hybrid Benzin/Elektro" },
  { value: "phev-diesel", label: "Plug-in hybrid Diesel/Elektro" },
  { value: "phev-petrol", label: "Plug-in hybrid Benzin/Elektro" },
  { value: "hev-diesel", label: "Voll-Hybrid Diesel/Elektro" },
  { value: "hev-petrol", label: "Voll-Hybrid Benzin/Elektro" },
] as const;

export const utilityExtrasEnum = [
  { value: "8-tyres", label: "8-fach bereift" },
  { value: "car-transporter", label: "Autotransporter" },
  { value: "accessible-for-disabled", label: "Behindertengerecht" },
  { value: "tarpaulin", label: "Blache/Plane" },
  { value: "direct-import", label: "Direkt-/Parallelimport" },
  { value: "tail-lift", label: "Hebebühne" },
  { value: "crane", label: "Kran" },
  { value: "refrigerator", label: "Kühlwagen" },
  { value: "furniture-transporter", label: "Möbeltransporter" },
  { value: "school-bus", label: "Schulbus" },
  { value: "winch", label: "Seilwinde" },
  { value: "accident-vehicle", label: "Unfallfahrzeug" },
] as const;
